package kr.lunaf.cloudislands.coreclient;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import kr.lunaf.cloudislands.api.model.CreateIslandResult;
import kr.lunaf.cloudislands.api.model.DeleteIslandResult;
import kr.lunaf.cloudislands.api.model.IslandFlag;
import kr.lunaf.cloudislands.api.model.IslandLocation;
import kr.lunaf.cloudislands.api.model.IslandRole;
import kr.lunaf.cloudislands.api.model.RouteTicket;
import kr.lunaf.cloudislands.protocol.job.IslandJob;
import kr.lunaf.cloudislands.protocol.job.IslandJobType;
import kr.lunaf.cloudislands.protocol.node.NodeHeartbeatRequest;
import kr.lunaf.cloudislands.protocol.session.PlayerRouteSession;

public interface CoreApiClient {
    CompletableFuture<CreateIslandResult> createIsland(UUID playerUuid, String templateId);
    CompletableFuture<DeleteIslandResult> deleteIsland(UUID requesterUuid, UUID islandId);
    CompletableFuture<String> listIslandMembers(UUID islandId);
    CompletableFuture<Void> setIslandMember(UUID islandId, UUID actorUuid, UUID playerUuid, IslandRole role);
    CompletableFuture<Void> removeIslandMember(UUID islandId, UUID actorUuid, UUID playerUuid);
    CompletableFuture<String> createIslandInvite(UUID islandId, UUID inviterUuid, UUID targetUuid);
    CompletableFuture<String> listPendingInvites(UUID playerUuid);
    CompletableFuture<Void> acceptIslandInvite(UUID inviteId, UUID playerUuid);
    CompletableFuture<Void> declineIslandInvite(UUID inviteId, UUID playerUuid);
    CompletableFuture<Void> banIslandVisitor(UUID islandId, UUID actorUuid, UUID playerUuid, String reason);
    CompletableFuture<Void> pardonIslandVisitor(UUID islandId, UUID actorUuid, UUID playerUuid);
    CompletableFuture<String> listIslandFlags(UUID islandId);
    CompletableFuture<Void> setIslandFlag(UUID islandId, UUID actorUuid, IslandFlag flag, String value);
    CompletableFuture<String> listIslandWarps(UUID islandId);
    CompletableFuture<Void> setIslandWarp(UUID islandId, UUID actorUuid, String name, IslandLocation location, boolean publicAccess);
    CompletableFuture<Void> deleteIslandWarp(UUID islandId, UUID actorUuid, String name);
    CompletableFuture<Void> setIslandPublicAccess(UUID islandId, UUID actorUuid, boolean publicAccess);
    CompletableFuture<Void> recordBlockDelta(UUID islandId, String materialKey, long delta);
    CompletableFuture<String> recalculateIslandLevel(UUID islandId);
    CompletableFuture<String> topIslandsByLevel(int limit);
    CompletableFuture<String> topIslandsByWorth(int limit);
    CompletableFuture<Void> setBlockValue(UUID actorUuid, String materialKey, String worth, long levelPoints, long limit);
    CompletableFuture<String> listUpgradeRules();
    CompletableFuture<String> listIslandUpgrades(UUID islandId);
    CompletableFuture<String> purchaseIslandUpgrade(UUID islandId, UUID actorUuid, String upgradeKey);
    CompletableFuture<String> listIslandSnapshots(UUID islandId, int limit);
    CompletableFuture<Void> requestIslandSnapshot(UUID islandId, String reason);
    CompletableFuture<Void> restoreIslandSnapshot(UUID islandId, long snapshotNo);
    CompletableFuture<String> listIslandLogs(UUID islandId, int limit);
    CompletableFuture<String> islandBank(UUID islandId);
    CompletableFuture<String> depositIslandBank(UUID islandId, UUID actorUuid, String amount);
    CompletableFuture<String> withdrawIslandBank(UUID islandId, UUID actorUuid, String amount);
    CompletableFuture<RouteTicket> createHomeTicket(UUID playerUuid);
    CompletableFuture<RouteTicket> createVisitTicket(UUID visitorUuid, UUID targetIslandId);
    CompletableFuture<RouteTicket> createRandomVisitTicket(UUID visitorUuid);
    CompletableFuture<RouteTicket> createWarpTicket(UUID playerUuid, UUID islandId, String warpName);
    CompletableFuture<Void> publishRouteSession(RouteTicket ticket);
    CompletableFuture<Optional<PlayerRouteSession>> consumeRouteSession(UUID playerUuid, String nodeId);
    CompletableFuture<Optional<RouteTicket>> consumeTicket(UUID ticketId, UUID playerUuid, String nodeId, String nonce);
    CompletableFuture<List<IslandJob>> claimJobs(String nodeId, List<IslandJobType> supportedTypes, int maxJobs);
    CompletableFuture<Void> completeJob(String nodeId, UUID jobId);
    CompletableFuture<Void> completeJob(String nodeId, UUID jobId, Map<String, String> payload);
    CompletableFuture<Void> failJob(String nodeId, UUID jobId, String errorMessage);
    CompletableFuture<Void> publishHeartbeat(NodeHeartbeatRequest request);
}
