package kr.lunaf.cloudislands.coreclient;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import kr.lunaf.cloudislands.api.model.CreateIslandResult;
import kr.lunaf.cloudislands.api.model.DeleteIslandResult;
import kr.lunaf.cloudislands.api.model.IslandFlag;
import kr.lunaf.cloudislands.api.model.IslandLocation;
import kr.lunaf.cloudislands.api.model.IslandPermission;
import kr.lunaf.cloudislands.api.model.IslandRole;
import kr.lunaf.cloudislands.api.model.RouteTicket;
import kr.lunaf.cloudislands.protocol.job.IslandJob;
import kr.lunaf.cloudislands.protocol.job.IslandJobType;
import kr.lunaf.cloudislands.protocol.node.NodeHeartbeatRequest;
import kr.lunaf.cloudislands.protocol.session.PlayerRouteSession;

public interface CoreApiClient {
    CompletableFuture<CreateIslandResult> createIsland(UUID playerUuid, String templateId);
    CompletableFuture<DeleteIslandResult> deleteIsland(UUID requesterUuid, UUID islandId);
    CompletableFuture<String> resetIsland(UUID islandId, UUID actorUuid, String reason);
    CompletableFuture<String> resetIslandResult(UUID islandId, UUID actorUuid, String reason);
    CompletableFuture<String> islandInfo(UUID islandId);
    CompletableFuture<String> islandInfoByOwner(UUID ownerUuid);
    CompletableFuture<String> islandInfoByName(String name);
    CompletableFuture<String> listIslandMembers(UUID islandId);
    CompletableFuture<Void> setIslandMember(UUID islandId, UUID actorUuid, UUID playerUuid, IslandRole role);
    CompletableFuture<String> setIslandMemberResult(UUID islandId, UUID actorUuid, UUID playerUuid, IslandRole role);
    CompletableFuture<Void> transferIslandOwnership(UUID islandId, UUID actorUuid, UUID targetUuid);
    CompletableFuture<String> transferIslandOwnershipResult(UUID islandId, UUID actorUuid, UUID targetUuid);
    CompletableFuture<Void> removeIslandMember(UUID islandId, UUID actorUuid, UUID playerUuid);
    CompletableFuture<String> removeIslandMemberResult(UUID islandId, UUID actorUuid, UUID playerUuid);
    CompletableFuture<String> createIslandInvite(UUID islandId, UUID inviterUuid, UUID targetUuid);
    CompletableFuture<String> listPendingInvites(UUID playerUuid);
    CompletableFuture<String> listPlayerIslands(UUID playerUuid);
    CompletableFuture<Void> acceptIslandInvite(UUID inviteId, UUID playerUuid);
    CompletableFuture<String> acceptIslandInviteResult(UUID inviteId, UUID playerUuid);
    CompletableFuture<Void> declineIslandInvite(UUID inviteId, UUID playerUuid);
    CompletableFuture<String> declineIslandInviteResult(UUID inviteId, UUID playerUuid);
    CompletableFuture<Void> banIslandVisitor(UUID islandId, UUID actorUuid, UUID playerUuid, String reason);
    CompletableFuture<String> banIslandVisitorResult(UUID islandId, UUID actorUuid, UUID playerUuid, String reason);
    CompletableFuture<String> listIslandBans(UUID islandId);
    CompletableFuture<Void> pardonIslandVisitor(UUID islandId, UUID actorUuid, UUID playerUuid);
    CompletableFuture<String> pardonIslandVisitorResult(UUID islandId, UUID actorUuid, UUID playerUuid);
    CompletableFuture<Void> kickIslandVisitor(UUID islandId, UUID actorUuid, UUID playerUuid);
    CompletableFuture<String> kickIslandVisitorResult(UUID islandId, UUID actorUuid, UUID playerUuid);
    CompletableFuture<String> listIslandFlags(UUID islandId);
    CompletableFuture<Void> setIslandFlag(UUID islandId, UUID actorUuid, IslandFlag flag, String value);
    CompletableFuture<String> setIslandFlagResult(UUID islandId, UUID actorUuid, IslandFlag flag, String value);
    CompletableFuture<String> islandBiome(UUID islandId);
    CompletableFuture<Void> setIslandBiome(UUID islandId, UUID actorUuid, String biomeKey);
    CompletableFuture<String> setIslandBiomeResult(UUID islandId, UUID actorUuid, String biomeKey);
    CompletableFuture<String> listIslandHomes(UUID islandId);
    CompletableFuture<Void> setIslandHome(UUID islandId, UUID actorUuid, String name, IslandLocation location);
    CompletableFuture<String> setIslandHomeResult(UUID islandId, UUID actorUuid, String name, IslandLocation location);
    CompletableFuture<String> listIslandPermissions(UUID islandId);
    CompletableFuture<Void> setIslandPermission(UUID islandId, UUID actorUuid, IslandRole role, IslandPermission permission, boolean allowed);
    CompletableFuture<String> setIslandPermissionResult(UUID islandId, UUID actorUuid, IslandRole role, IslandPermission permission, boolean allowed);
    CompletableFuture<String> listIslandWarps(UUID islandId);
    CompletableFuture<String> listPublicWarps(int limit);
    CompletableFuture<Void> setIslandWarp(UUID islandId, UUID actorUuid, String name, IslandLocation location, boolean publicAccess);
    CompletableFuture<String> setIslandWarpResult(UUID islandId, UUID actorUuid, String name, IslandLocation location, boolean publicAccess);
    CompletableFuture<Void> deleteIslandWarp(UUID islandId, UUID actorUuid, String name);
    CompletableFuture<String> deleteIslandWarpResult(UUID islandId, UUID actorUuid, String name);
    CompletableFuture<Void> setIslandWarpPublicAccess(UUID islandId, UUID actorUuid, String name, boolean publicAccess);
    CompletableFuture<String> setIslandWarpPublicAccessResult(UUID islandId, UUID actorUuid, String name, boolean publicAccess);
    CompletableFuture<Void> setIslandPublicAccess(UUID islandId, UUID actorUuid, boolean publicAccess);
    CompletableFuture<String> setIslandPublicAccessResult(UUID islandId, UUID actorUuid, boolean publicAccess);
    CompletableFuture<Void> setIslandLocked(UUID islandId, UUID actorUuid, boolean locked);
    CompletableFuture<String> setIslandLockedResult(UUID islandId, UUID actorUuid, boolean locked);
    CompletableFuture<Void> recordBlockDelta(UUID islandId, String materialKey, long delta);
    CompletableFuture<String> recordBlockDeltaResult(UUID islandId, String materialKey, long delta);
    CompletableFuture<String> replaceBlockCounts(UUID islandId, Map<String, Long> counts);
    CompletableFuture<String> recalculateIslandLevel(UUID islandId, UUID actorUuid);
    CompletableFuture<String> topIslandsByLevel(int limit);
    CompletableFuture<String> topIslandsByWorth(int limit);
    CompletableFuture<String> listPublicIslands(int limit);
    CompletableFuture<Void> setBlockValue(UUID actorUuid, String materialKey, String worth, long levelPoints, long limit);
    CompletableFuture<String> setBlockValueResult(UUID actorUuid, String materialKey, String worth, long levelPoints, long limit);
    CompletableFuture<String> listBlockValues();
    CompletableFuture<String> listUpgradeRules();
    CompletableFuture<String> listIslandUpgrades(UUID islandId);
    CompletableFuture<String> purchaseIslandUpgrade(UUID islandId, UUID actorUuid, String upgradeKey);
    CompletableFuture<String> listIslandMissions(UUID islandId, String kind);
    default CompletableFuture<String> completeIslandMission(UUID islandId, UUID actorUuid, String missionKey) {
        return completeIslandMission(islandId, actorUuid, missionKey, "MISSION");
    }
    CompletableFuture<String> completeIslandMission(UUID islandId, UUID actorUuid, String missionKey, String kind);
    CompletableFuture<String> listIslandLimits(UUID islandId);
    CompletableFuture<String> setIslandLimit(UUID islandId, UUID actorUuid, String limitKey, long value);
    CompletableFuture<String> sendIslandChat(UUID islandId, UUID actorUuid, String channel, String message);
    CompletableFuture<String> listIslandSnapshots(UUID islandId, int limit);
    CompletableFuture<Void> requestIslandSnapshot(UUID islandId, String reason);
    CompletableFuture<String> requestIslandSnapshotResult(UUID islandId, String reason);
    CompletableFuture<Void> restoreIslandSnapshot(UUID islandId, long snapshotNo);
    CompletableFuture<String> restoreIslandSnapshotResult(UUID islandId, long snapshotNo);
    CompletableFuture<String> listIslandLogs(UUID islandId, int limit);
    CompletableFuture<String> islandBank(UUID islandId);
    CompletableFuture<String> depositIslandBank(UUID islandId, UUID actorUuid, String amount);
    CompletableFuture<String> withdrawIslandBank(UUID islandId, UUID actorUuid, String amount);
    CompletableFuture<RouteTicket> createHomeTicket(UUID playerUuid);
    CompletableFuture<RouteTicket> createHomeTicket(UUID playerUuid, String homeName);
    CompletableFuture<RouteTicket> createVisitTicket(UUID visitorUuid, UUID targetIslandId);
    CompletableFuture<RouteTicket> createRandomVisitTicket(UUID visitorUuid);
    CompletableFuture<RouteTicket> createWarpTicket(UUID playerUuid, UUID islandId, String warpName);
    CompletableFuture<Void> publishRouteSession(RouteTicket ticket);
    CompletableFuture<String> publishRouteSessionResult(RouteTicket ticket);
    CompletableFuture<Optional<PlayerRouteSession>> consumeRouteSession(UUID playerUuid, String nodeId);
    CompletableFuture<Optional<RouteTicket>> routeTicketStatus(UUID ticketId, UUID playerUuid, String nonce);
    CompletableFuture<Optional<RouteTicket>> consumeTicket(UUID ticketId, UUID playerUuid, String nodeId, String nonce);
    CompletableFuture<String> listNodes();
    CompletableFuture<String> nodeInfo(String nodeId);
    CompletableFuture<String> nodeIslands(String nodeId, int limit);
    CompletableFuture<String> drainNode(String nodeId);
    CompletableFuture<String> drainNodeResult(String nodeId);
    CompletableFuture<String> undrainNode(String nodeId);
    CompletableFuture<String> undrainNodeResult(String nodeId);
    CompletableFuture<String> sweepNode(String nodeId);
    CompletableFuture<String> sweepNodeResult(String nodeId);
    CompletableFuture<String> kickAllNode(String nodeId, String reason);
    CompletableFuture<String> kickAllNodeResult(String nodeId, String reason);
    CompletableFuture<String> shutdownNodeSafely(String nodeId, String reason);
    CompletableFuture<String> shutdownNodeSafelyResult(String nodeId, String reason);
    CompletableFuture<String> activateIsland(UUID islandId);
    CompletableFuture<String> activateIslandResult(UUID islandId);
    CompletableFuture<String> deactivateIsland(UUID islandId);
    CompletableFuture<String> deactivateIslandResult(UUID islandId);
    CompletableFuture<String> migrateIsland(UUID islandId, String targetNode);
    CompletableFuture<String> migrateIslandResult(UUID islandId, String targetNode);
    CompletableFuture<String> quarantineIsland(UUID islandId, String reason);
    CompletableFuture<String> quarantineIslandResult(UUID islandId, String reason);
    CompletableFuture<String> adminIslandInfo(UUID lookupUuid);
    CompletableFuture<String> adminIslandWhere(UUID islandId);
    CompletableFuture<RouteTicket> adminIslandTeleport(UUID playerUuid, UUID islandId);
    CompletableFuture<String> adminDeleteIsland(UUID islandId);
    CompletableFuture<String> adminDeleteIslandResult(UUID islandId);
    CompletableFuture<String> repairIsland(UUID islandId, String reason);
    CompletableFuture<String> repairIslandResult(UUID islandId, String reason);
    CompletableFuture<String> debugRoutes(UUID playerUuid);
    CompletableFuture<String> routeTicket(UUID ticketId);
    CompletableFuture<String> routeTicketForPlayer(UUID playerUuid);
    CompletableFuture<String> clearRoute(UUID playerUuid, UUID ticketId);
    CompletableFuture<String> clearRouteResult(UUID playerUuid, UUID ticketId);
    CompletableFuture<String> listEvents();
    CompletableFuture<String> listEvents(int limit);
    CompletableFuture<String> listAuditLogs();
    CompletableFuture<String> metrics();
    CompletableFuture<String> clearCache();
    CompletableFuture<String> clearCacheResult();
    CompletableFuture<String> reload();
    CompletableFuture<String> reloadResult();
    CompletableFuture<String> migrateSuperiorSkyblock2(String action, String path);
    CompletableFuture<String> playerInfo(UUID playerUuid);
    CompletableFuture<String> playerInfoByName(String lastName);
    CompletableFuture<String> touchPlayerProfile(UUID playerUuid, String lastName);
    CompletableFuture<String> setPlayerIsland(UUID playerUuid, UUID islandId);
    CompletableFuture<String> clearPlayerIsland(UUID playerUuid);
    CompletableFuture<String> listTemplates();
    CompletableFuture<String> upsertTemplate(String templateId, String displayName, boolean enabled, String minNodeVersion);
    CompletableFuture<String> enableTemplate(String templateId);
    CompletableFuture<String> disableTemplate(String templateId);
    CompletableFuture<List<IslandJob>> claimJobs(String nodeId, List<IslandJobType> supportedTypes, int maxJobs);
    CompletableFuture<String> listJobs();
    CompletableFuture<String> retryJob(UUID jobId);
    CompletableFuture<String> retryJobResult(UUID jobId);
    CompletableFuture<String> cancelJob(UUID jobId);
    CompletableFuture<String> cancelJobResult(UUID jobId);
    CompletableFuture<String> recoverJobs(String nodeId, long minIdleMillis, int maxJobs);
    CompletableFuture<String> recoverJobsResult(String nodeId, long minIdleMillis, int maxJobs);
    CompletableFuture<Void> completeJob(String nodeId, UUID jobId);
    CompletableFuture<Void> completeJob(String nodeId, UUID jobId, Map<String, String> payload);
    CompletableFuture<String> completeJobResult(String nodeId, UUID jobId, Map<String, String> payload);
    CompletableFuture<Void> failJob(String nodeId, UUID jobId, String errorMessage);
    CompletableFuture<String> failJobResult(String nodeId, UUID jobId, String errorMessage);
    CompletableFuture<Void> publishHeartbeat(NodeHeartbeatRequest request);
    CompletableFuture<String> publishHeartbeatResult(NodeHeartbeatRequest request);
}
