version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependency-update"
      - "runtime-canary"
    commit-message:
      prefix: "canary"
