package kr.lunaf.cloudislands.common.event;

public enum CloudIslandEventType {
    ISLAND_CREATED,
    ISLAND_DELETE_REQUESTED,
    ISLAND_DELETED,
    ISLAND_ACTIVATED,
    ISLAND_DEACTIVATE_REQUESTED,
    ISLAND_DEACTIVATED,
    ISLAND_MIGRATE_REQUESTED,
    ISLAND_MIGRATED,
    ISLAND_MEMBER_CHANGED,
    ISLAND_FLAG_CHANGED,
    ISLAND_PERMISSION_CHANGED,
    ISLAND_WARP_CHANGED,
    ISLAND_RUNTIME_CHANGED,
    ISLAND_LEVEL_UPDATED,
    ISLAND_UPGRADE,
    ISLAND_SNAPSHOT_REQUESTED,
    ISLAND_SNAPSHOT_CREATED,
    NODE_STATE_CHANGED,
    ROUTE_TICKET_CREATED,
    ROUTE_TICKET_CONSUMED,
    ROUTE_TICKET_FAILED
}
