package kr.lunaf.cloudislands.api.service;

import java.util.List;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import kr.lunaf.cloudislands.api.model.AuditLogSnapshot;
import kr.lunaf.cloudislands.api.model.CoreMaintenanceResult;
import kr.lunaf.cloudislands.api.model.GlobalEventSnapshot;
import kr.lunaf.cloudislands.api.model.IslandActionResult;
import kr.lunaf.cloudislands.api.model.IslandJobSnapshot;
import kr.lunaf.cloudislands.api.model.IslandNodeSnapshot;
import kr.lunaf.cloudislands.api.model.IslandRuntimeSnapshot;
import kr.lunaf.cloudislands.api.model.IslandTemplateSnapshot;
import kr.lunaf.cloudislands.api.model.JobRecoveryResult;
import kr.lunaf.cloudislands.api.model.MigrationRunSnapshot;
import kr.lunaf.cloudislands.api.model.NodeSweepResult;
import kr.lunaf.cloudislands.api.model.PlayerIslandProfile;
import kr.lunaf.cloudislands.api.model.PlayerRouteSessionSnapshot;
import kr.lunaf.cloudislands.api.model.RouteClearResult;
import kr.lunaf.cloudislands.api.model.RouteTicket;

public interface IslandAdminService {
    CompletableFuture<Void> drainNode(String nodeId);
    CompletableFuture<IslandActionResult> drainNodeResult(String nodeId);
    CompletableFuture<Void> undrainNode(String nodeId);
    CompletableFuture<IslandActionResult> undrainNodeResult(String nodeId);
    CompletableFuture<Void> sweepNode(String nodeId);
    CompletableFuture<NodeSweepResult> sweepNodeResult(String nodeId);
    CompletableFuture<Void> migrateIsland(UUID islandId, String targetNode);
    CompletableFuture<IslandActionResult> migrateIslandResult(UUID islandId, String targetNode);
    CompletableFuture<Void> snapshotIsland(UUID islandId, String reason);
    CompletableFuture<IslandActionResult> snapshotIslandResult(UUID islandId, String reason);
    CompletableFuture<Void> restoreIsland(UUID islandId, long snapshotNo);
    CompletableFuture<IslandActionResult> restoreIslandResult(UUID islandId, long snapshotNo);
    CompletableFuture<Void> quarantineIsland(UUID islandId, String reason);
    CompletableFuture<IslandActionResult> quarantineIslandResult(UUID islandId, String reason);
    CompletableFuture<Void> repairIsland(UUID islandId, String reason);
    CompletableFuture<java.util.Optional<IslandRuntimeSnapshot>> repairIslandResult(UUID islandId, String reason);
    CompletableFuture<Void> deleteIsland(UUID islandId);
    CompletableFuture<IslandActionResult> adminDeleteIslandResult(UUID islandId);
    CompletableFuture<RouteTicket> createAdminTeleportTicket(UUID playerUuid, UUID islandId);
    CompletableFuture<java.util.Optional<RouteTicket>> getRouteTicket(UUID ticketId);
    CompletableFuture<java.util.Optional<PlayerRouteSessionSnapshot>> getRouteSession(UUID playerUuid);
    CompletableFuture<Void> clearRoute(UUID playerUuid, UUID ticketId);
    CompletableFuture<RouteClearResult> clearRouteResult(UUID playerUuid, UUID ticketId);
    CompletableFuture<List<IslandJobSnapshot>> listJobs();
    CompletableFuture<Void> retryJob(UUID jobId);
    CompletableFuture<IslandActionResult> retryJobResult(UUID jobId);
    CompletableFuture<Void> cancelJob(UUID jobId);
    CompletableFuture<IslandActionResult> cancelJobResult(UUID jobId);
    CompletableFuture<Void> recoverJobs(String nodeId, long minIdleMillis, int maxJobs);
    CompletableFuture<JobRecoveryResult> recoverJobsResult(String nodeId, long minIdleMillis, int maxJobs);
    CompletableFuture<Void> clearCache();
    CompletableFuture<CoreMaintenanceResult> clearCacheResult();
    CompletableFuture<Void> reload();
    CompletableFuture<CoreMaintenanceResult> reloadResult();
    CompletableFuture<java.util.Optional<PlayerIslandProfile>> getPlayerProfile(UUID playerUuid);
    CompletableFuture<java.util.Optional<PlayerIslandProfile>> setPlayerPrimaryIsland(UUID playerUuid, UUID islandId);
    CompletableFuture<java.util.Optional<PlayerIslandProfile>> clearPlayerPrimaryIsland(UUID playerUuid);
    CompletableFuture<Void> setBlockValue(UUID actorUuid, String materialKey, String worth, long levelPoints, long limit);
    CompletableFuture<IslandActionResult> setBlockValueResult(UUID actorUuid, String materialKey, String worth, long levelPoints, long limit);
    CompletableFuture<List<GlobalEventSnapshot>> listEvents();
    CompletableFuture<List<AuditLogSnapshot>> listAuditLogs();
    CompletableFuture<List<String>> listNodes();
    CompletableFuture<List<IslandNodeSnapshot>> listNodeSnapshots();
    CompletableFuture<java.util.Optional<IslandNodeSnapshot>> getNodeSnapshot(String nodeId);
    CompletableFuture<List<IslandTemplateSnapshot>> listTemplates();
    CompletableFuture<IslandTemplateSnapshot> upsertTemplate(String templateId, String displayName, boolean enabled, String minNodeVersion);
    CompletableFuture<IslandTemplateSnapshot> enableTemplate(String templateId);
    CompletableFuture<IslandTemplateSnapshot> disableTemplate(String templateId);
    CompletableFuture<MigrationRunSnapshot> scanSuperiorSkyblock2(String path);
    CompletableFuture<MigrationRunSnapshot> dryRunSuperiorSkyblock2(String path);
    CompletableFuture<MigrationRunSnapshot> importSuperiorSkyblock2(String path);
    CompletableFuture<MigrationRunSnapshot> verifySuperiorSkyblock2(String path);
    CompletableFuture<MigrationRunSnapshot> rollbackSuperiorSkyblock2(String path);
}
