apiVersion: v1
kind: Service
metadata:
  name: cloudislands-core
spec:
  selector:
    app.kubernetes.io/component: core
  ports:
    - name: http
      port: {{ .Values.core.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: cloudislands-velocity
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: velocity
  ports:
    - name: minecraft
      port: {{ .Values.velocity.port }}
      targetPort: minecraft
---
apiVersion: v1
kind: Service
metadata:
  name: cloudislands-postgres
spec:
  selector:
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: cloudislands-redis
spec:
  selector:
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
---
apiVersion: v1
kind: Service
metadata:
  name: cloudislands-object-storage
spec:
  selector:
    app.kubernetes.io/component: object-storage
  ports:
    - name: s3
      port: 9000
      targetPort: s3
