package kr.lunaf.cloudislands.api.upgrade;

public enum UpgradeType {
    ISLAND_SIZE,
    MAX_MEMBERS,
    MAX_WARPS,
    HOPPER_LIMIT,
    SPAWNER_LIMIT,
    GENERATOR_LEVEL,
    MOB_LIMIT,
    CROP_GROWTH,
    FLY_ACCESS,
    REDSTONE_LIMIT,
    BANK_LIMIT,
    MEMBER_LIMIT,
    WARP_LIMIT,
    HOME_LIMIT,
    BORDER_SIZE,
    BORDER_COLOR_UNLOCK,
    BIOME_UNLOCK,
    KEEP_INVENTORY_ENABLE
}
