package kr.lunaf.cloudislands.paper.gui;

import java.util.Set;

public final class GuiActionSchema {
    private static final Set<String> REGISTERED_ACTIONS = Set.of(
        "admin.island.migrate.prompt",
        "admin.island.where.prompt",
        "admin.node.drain",
        "admin.node.info",
        "admin.node.islands",
        "admin.node.kickall.confirm",
        "admin.node.kickall.prepare",
        "admin.node.list",
        "admin.node.open",
        "admin.node.shutdown-safe.confirm",
        "admin.node.shutdown-safe.prepare",
        "admin.node.sweep",
        "admin.node.undrain",
        "gui.close",
        "island.ban.pardon.confirm",
        "island.ban.pardon.prepare",
        "island.bank.deposit",
        "island.bank.open",
        "island.bank.withdraw",
        "island.bans.list",
        "island.bans.open",
        "island.biome.open",
        "island.biome.set",
        "island.biome.show",
        "island.chat.open",
        "island.create",
        "island.create.open",
        "island.danger.delete.confirm",
        "island.danger.delete.prepare",
        "island.danger.open",
        "island.danger.reset.confirm",
        "island.danger.reset.prepare",
        "island.flag.set",
        "island.flags.list",
        "island.flags.open",
        "island.home",
        "island.home.set",
        "island.homes.open",
        "island.info.open",
        "island.invite.accept",
        "island.invite.decline",
        "island.invites.open",
        "island.level.recalculate",
        "island.level.show",
        "island.limit.set",
        "island.limits.list",
        "island.limits.open",
        "island.list.open",
        "island.lock.toggle",
        "island.log.detail",
        "island.logs.list",
        "island.logs.open",
        "island.main.open",
        "island.member.demote",
        "island.member.demote.prepare",
        "island.member.detail",
        "island.member.invite",
        "island.member.invite.help",
        "island.member.list",
        "island.member.promote",
        "island.member.promote.prepare",
        "island.member.remove.confirm",
        "island.member.remove.prepare",
        "island.member.role",
        "island.members.open",
        "island.members.page",
        "island.mission.complete",
        "island.missions.open",
        "island.permissions.list",
        "island.permissions.open",
        "island.permissions.page",
        "island.permissions.reset",
        "island.permissions.save",
        "island.permissions.set",
        "island.public.toggle",
        "island.ranking.list",
        "island.ranking.open",
        "island.role.weight.adjust",
        "island.roles.list",
        "island.roles.open",
        "island.settings.open",
        "island.snapshot.create",
        "island.snapshot.restore.confirm",
        "island.snapshot.restore.prepare",
        "island.snapshots.list",
        "island.snapshots.open",
        "island.upgrade.purchase",
        "island.upgrades.list",
        "island.upgrades.open",
        "island.visit.open",
        "island.visit.public.open",
        "island.visit.random",
        "island.visit.target",
        "island.warp.delete.confirm",
        "island.warp.delete.prepare",
        "island.warp.private",
        "island.warp.public",
        "island.warp.public.toggle",
        "island.warp.teleport",
        "island.warps.open",
        "island.worth.show"
    );

    private GuiActionSchema() {
    }

    public static Set<String> registeredActionIds() {
        return REGISTERED_ACTIONS;
    }

    public static boolean registered(String actionId) {
        return actionId != null && REGISTERED_ACTIONS.contains(actionId.trim());
    }
}
