ALTER TABLE island_permissions
    DROP CONSTRAINT IF EXISTS chk_island_permissions_key_known;

ALTER TABLE island_permissions
    ADD CONSTRAINT chk_island_permissions_key_known
    CHECK (permission_key IN (
        'BUILD',
        'BREAK',
        'INTERACT',
        'OPEN_CONTAINER',
        'USE_DOOR',
        'USE_BUTTON',
        'USE_PRESSURE_PLATE',
        'USE_REDSTONE',
        'PLACE_LIQUID',
        'BREAK_LIQUID',
        'ATTACK_PLAYER',
        'ATTACK_MOB',
        'PICKUP_ITEM',
        'DROP_ITEM',
        'FERTILIZE',
        'ANIMAL_BREED',
        'ANIMAL_SHEAR',
        'FISH',
        'ENTITY_RIDE',
        'VILLAGER_TRADE',
        'PICKUP_ENTITY_BUCKET',
        'TAKE_LECTERN_BOOK',
        'DYE_SHEEP',
        'SADDLE_ENTITY',
        'BRUSH',
        'ENDER_PEARL',
        'CHORUS_FRUIT',
        'BREAK_SPAWNER',
        'PAINTING',
        'TURTLE_EGG_TRAMPLE',
        'WIND_CHARGE',
        'IGNITE_CREEPER',
        'NAME_ENTITY',
        'SCULK_SENSOR',
        'TRIGGER_RAID',
        'USE_SPAWNER',
        'USE_ANVIL',
        'USE_ENCHANT_TABLE',
        'USE_BREWING_STAND',
        'MANAGE_MEMBERS',
        'MANAGE_ROLES',
        'MANAGE_FLAGS',
        'MANAGE_WARPS',
        'MANAGE_UPGRADES',
        'START_LEVEL_CALC',
        'BAN_VISITOR',
        'KICK_VISITOR',
        'SET_HOME',
        'SET_BIOME',
        'WITHDRAW_BANK',
        'DEPOSIT_BANK'
    ));

ALTER TABLE island_permission_overrides
    DROP CONSTRAINT IF EXISTS chk_island_permission_override_key_known;

ALTER TABLE island_permission_overrides
    ADD CONSTRAINT chk_island_permission_override_key_known
    CHECK (permission_key IN (
        'BUILD',
        'BREAK',
        'INTERACT',
        'OPEN_CONTAINER',
        'USE_DOOR',
        'USE_BUTTON',
        'USE_PRESSURE_PLATE',
        'USE_REDSTONE',
        'PLACE_LIQUID',
        'BREAK_LIQUID',
        'ATTACK_PLAYER',
        'ATTACK_MOB',
        'PICKUP_ITEM',
        'DROP_ITEM',
        'FERTILIZE',
        'ANIMAL_BREED',
        'ANIMAL_SHEAR',
        'FISH',
        'ENTITY_RIDE',
        'VILLAGER_TRADE',
        'PICKUP_ENTITY_BUCKET',
        'TAKE_LECTERN_BOOK',
        'DYE_SHEEP',
        'SADDLE_ENTITY',
        'BRUSH',
        'ENDER_PEARL',
        'CHORUS_FRUIT',
        'BREAK_SPAWNER',
        'PAINTING',
        'TURTLE_EGG_TRAMPLE',
        'WIND_CHARGE',
        'IGNITE_CREEPER',
        'NAME_ENTITY',
        'SCULK_SENSOR',
        'TRIGGER_RAID',
        'USE_SPAWNER',
        'USE_ANVIL',
        'USE_ENCHANT_TABLE',
        'USE_BREWING_STAND',
        'MANAGE_MEMBERS',
        'MANAGE_ROLES',
        'MANAGE_FLAGS',
        'MANAGE_WARPS',
        'MANAGE_UPGRADES',
        'START_LEVEL_CALC',
        'BAN_VISITOR',
        'KICK_VISITOR',
        'SET_HOME',
        'SET_BIOME',
        'WITHDRAW_BANK',
        'DEPOSIT_BANK'
    ));

