package kr.lunaf.cloudislands.paper.admin;

import java.util.List;
import kr.lunaf.cloudislands.common.feature.SuperiorSkyblockReplacementFeaturePolicy;

final class AdminCommandCatalog {
    static final List<String> ROOT_COMMANDS = List.of("help", "commands", "command", "command-list", "명령어", "명령어목록", "status", "dashboard", "doctor", "setup", "config", "cache", "addons", "integrations", "node", "island", "player", "jobs", "route", "rankings", "events", "audit", "metrics", "storage", "diagnostics", "support-bundle", "block-values", "upgrade-rules", "setblockamount", "seteffect", "setcropgrowth", "setmobdrops", "setspawnerrates", "template", "templates", "migrate-superiorskyblock2", "reload");
    static final List<String> SETUP_COMMANDS = List.of("start", "core", "redis", "database", "storage", "velocity", "paper-node", "verify");
    static final List<String> CONFIG_COMMANDS = List.of("show", "validate", "diff", "reload", "effective", "sources");
    static final List<String> CACHE_COMMANDS = List.of("clear");
    static final List<String> ADDON_COMMANDS = List.of("list", "info", "feature", "enable", "disable", "reload", "state", "state-summary", "endpoints");
    static final List<String> ADDON_FEATURES = List.of("commands", "machines", "storage", "factories", "generators", "upgrades", "missions", "menus", "gui", "lifecycle", "resource-nodes", "market", "contracts", "research", "maintenance", "placeholders", "migration", "addon-state", "route-events");
    static final List<String> NODE_COMMANDS = List.of("menu", "list", "info", "islands", "drain", "undrain", "sweep", "kickall", "shutdown-safe");
    static final List<String> ISLAND_COMMANDS = List.of("info", "where", "inspect", "visitor-stats", "visitors", "tp", "activate", "deactivate", "migrate", "save", "snapshot", "snapshots", "restore", "rollback", "bulk-restore", "bank", "member", "rename", "setbiome", "biome", "delwarp", "deletewarp", "setgenerator", "addgenerator", "cleargenerator", "setbanklimit", "addbanklimit", "setentitylimit", "addentitylimit", "setteamlimit", "addteamlimit", "setwarpslimit", "addwarpslimit", "setsize", "addsize", "ignore", "unignore", "setpermission", "resetpermissions", "quarantine", "recover", "repair", "delete");
    static final List<String> PLAYER_COMMANDS = List.of("info", "setisland", "clearisland");
    static final List<String> JOB_COMMANDS = List.of("list", "retry", "cancel", "recover");
    static final List<String> ROUTE_COMMANDS = List.of("debug", "ticket", "tickets", "clear");
    static final List<String> STORAGE_COMMANDS = List.of("status", "verify");
    static final List<String> DIAGNOSTICS_COMMANDS = List.of("export");
    static final List<String> SUPPORT_BUNDLE_COMMANDS = List.of("create");
    static final List<String> RANKING_COMMANDS = List.of("level", "worth");
    static final List<String> BLOCK_VALUE_COMMANDS = List.of("list", "search", "set", "reload");
    static final List<String> BLOCK_VALUE_MATERIALS = List.of("minecraft:stone", "minecraft:diamond_block", "minecraft:emerald_block", "minecraft:spawner");
    static final List<String> TEMPLATE_COMMANDS = List.of("list", "import", "import-bundle", "upsert", "seticon", "setcost", "setpermission", "enable", "disable", "preview", "validate", "verify-bundle", "verify", "delete", "reorder");
    static final List<String> MIGRATION_COMMANDS = List.of("wizard", "scan", "status", "dryrun", "dry-run", "report", "extract", "extract-worlds", "world-extract", "import", "verify", "compare", "verify-no-legacy-provider", "rollback");
    static final List<String> FORBIDDEN_LEGACY_SKYBLOCK_PROVIDERS = SuperiorSkyblockReplacementFeaturePolicy.forbiddenRuntimeProviders();
    static final List<String> NODE_DANGER_REASONS = List.of("maintenance", "restart", "drain");
    static final List<String> HELP_COMMANDS = List.of(
        "ciadmin status",
        "ciadmin dashboard",
        "ciadmin doctor",
        "ciadmin doctor --json",
        "ciadmin doctor --markdown",
        "ciadmin setup start",
        "ciadmin setup core",
        "ciadmin setup redis",
        "ciadmin setup database",
        "ciadmin setup storage",
        "ciadmin setup velocity",
        "ciadmin setup paper-node",
        "ciadmin setup verify",
        "ciadmin config",
        "ciadmin config validate",
        "ciadmin config diff",
        "ciadmin config reload",
        "ciadmin config effective",
        "ciadmin config sources",
        "ciadmin help [page]",
        "ciadmin command list [page]",
        "ciadmin cache clear",
        "ciadmin addons list",
        "ciadmin addons info <addonId>",
        "ciadmin addons feature <addonId> <feature>",
        "ciadmin addons feature <addonId> <feature> <true|false>",
        "ciadmin addons enable <addonId>",
        "ciadmin addons disable <addonId>",
        "ciadmin addons reload [addonId]",
        "ciadmin addons state",
        "ciadmin addons state-summary",
        "ciadmin addons endpoints",
        "ciadmin integrations",
        "ciadmin integrations report",
        "ciadmin node menu",
        "ciadmin node list",
        "ciadmin node info <node>",
        "ciadmin node islands <node> [limit]",
        "ciadmin node drain <node>",
        "ciadmin node undrain <node>",
        "ciadmin node sweep [node]",
        "ciadmin node kickall <node> [reason]",
        "ciadmin node shutdown-safe <node> [reason]",
        "ciadmin island info <island>",
        "ciadmin island where <player|island>",
        "ciadmin island inspect <player|island>",
        "ciadmin island inspect <player|island> --json",
        "ciadmin island visitor-stats <island>",
        "ciadmin island tp <island>",
        "ciadmin island activate <island>",
        "ciadmin island deactivate <island>",
        "ciadmin island migrate <island> <node>",
        "ciadmin island save <island>",
        "ciadmin island snapshot <island> [reason]",
        "ciadmin island snapshots <island>",
        "ciadmin island restore <island> <snapshot> --confirm",
        "ciadmin island rollback <island> <snapshot> --confirm",
        "ciadmin island bulk-restore <snapshot> <island...> --confirm",
        "ciadmin island bank deposit <island> <amount>",
        "ciadmin island bank withdraw <island> <amount>",
        "ciadmin island member add <island> <player> [role]",
        "ciadmin island member kick <island> <player>",
        "ciadmin island member promote <island> <player>",
        "ciadmin island member demote <island> <player>",
        "ciadmin island member setleader <island> <player>",
        "ciadmin island rename <island> <name>",
        "ciadmin island setbiome <island> <biomeKey>",
        "ciadmin island delwarp <island> <warp>",
        "ciadmin island setgenerator <island> <generatorKey> <level>",
        "ciadmin island addgenerator <island> <levels> [generatorKey]",
        "ciadmin island cleargenerator <island>",
        "ciadmin island setbanklimit <island> <value>",
        "ciadmin island addbanklimit <island> <delta>",
        "ciadmin island setentitylimit <island> <value>",
        "ciadmin island addentitylimit <island> <delta>",
        "ciadmin island setteamlimit <island> <value>",
        "ciadmin island addteamlimit <island> <delta>",
        "ciadmin island setwarpslimit <island> <value>",
        "ciadmin island addwarpslimit <island> <delta>",
        "ciadmin island setsize <island> <value>",
        "ciadmin island addsize <island> <delta>",
        "ciadmin island ignore <island>",
        "ciadmin island unignore <island>",
        "ciadmin island setpermission <island> <role> <permission> <true|false>",
        "ciadmin island resetpermissions <island> <role>",
        "ciadmin island quarantine <island> [reason]",
        "ciadmin island recover <island> [reason]",
        "ciadmin island repair <island> [reason]",
        "ciadmin island delete <island> --confirm",
        "ciadmin player info <player>",
        "ciadmin player setisland <player> <islandUuid>",
        "ciadmin player clearisland <player>",
        "ciadmin jobs list",
        "ciadmin jobs retry <jobId>",
        "ciadmin jobs cancel <jobId>",
        "ciadmin jobs recover [nodeId] [minIdleMillis] [maxJobs]",
        "ciadmin route debug [all|player]",
        "ciadmin route ticket <ticket|player>",
        "ciadmin route tickets <player>",
        "ciadmin route clear <player> [ticket]",
        "ciadmin rankings level [limit]",
        "ciadmin rankings worth [limit]",
        "ciadmin events",
        "ciadmin audit",
        "ciadmin metrics",
        "ciadmin storage",
        "ciadmin storage verify <island>",
        "ciadmin diagnostics export",
        "ciadmin support-bundle create",
        "ciadmin block-values list",
        "ciadmin block-values search <query> [limit]",
        "ciadmin block-values set <materialKey> <worth> <levelPoints> <limit>",
        "ciadmin block-values reload",
        "ciadmin upgrade-rules",
        "ciadmin setblockamount <island> <materialKey> <amount>",
        "ciadmin seteffect <island> <effectKey> <amplifier>",
        "ciadmin setcropgrowth <island> <percent>",
        "ciadmin setmobdrops <island> <percent>",
        "ciadmin setspawnerrates <island> <percent>",
        "ciadmin template list",
        "ciadmin template import <name>",
        "ciadmin template import-bundle <id> <bundlePath> <checksum> [sizeBytes] [displayName]",
        "ciadmin template upsert <id> <name> [enabled|disabled] [minNodeVersion]",
        "ciadmin template seticon <name> <material>",
        "ciadmin template setcost <name> <amount>",
        "ciadmin template setpermission <name> <permission>",
        "ciadmin template enable <id>",
        "ciadmin template disable <id>",
        "ciadmin template preview <id>",
        "ciadmin template validate <id>",
        "ciadmin template verify-bundle <id>",
        "ciadmin template delete <id> --confirm",
        "ciadmin template reorder <id> <sortOrder>",
        "ciadmin templates list",
        "ciadmin templates import <name>",
        "ciadmin templates import-bundle <id> <bundlePath> <checksum> [sizeBytes] [displayName]",
        "ciadmin templates upsert <id> <name> [enabled|disabled] [minNodeVersion]",
        "ciadmin templates seticon <name> <material>",
        "ciadmin templates setcost <name> <amount>",
        "ciadmin templates setpermission <name> <permission>",
        "ciadmin templates enable <id>",
        "ciadmin templates disable <id>",
        "ciadmin templates preview <id>",
        "ciadmin templates validate <id>",
        "ciadmin templates verify-bundle <id>",
        "ciadmin templates delete <id> --confirm",
        "ciadmin templates reorder <id> <sortOrder>",
        "ciadmin reload"
    );
    static final List<String> MIGRATION_HELP_COMMANDS = List.of(
        "ciadmin migrate-superiorskyblock2 wizard",
        "ciadmin migrate-superiorskyblock2 scan [path]",
        "ciadmin migrate-superiorskyblock2 status",
        "ciadmin migrate-superiorskyblock2 dryrun [path]",
        "ciadmin migrate-superiorskyblock2 dry-run [path]",
        "ciadmin migrate-superiorskyblock2 report",
        "ciadmin migrate-superiorskyblock2 extract [outputPath]",
        "ciadmin migrate-superiorskyblock2 import <approvalToken>",
        "ciadmin migrate-superiorskyblock2 verify [path]",
        "ciadmin migrate-superiorskyblock2 compare <island>",
        "ciadmin migrate-superiorskyblock2 verify-no-legacy-provider",
        "ciadmin migrate-superiorskyblock2 rollback"
    );

    private AdminCommandCatalog() {
    }
}
