package kr.lunaf.cloudislands.coreservice.http.routes;

import static kr.lunaf.cloudislands.coreservice.config.CoreIslandPoolSummary.*;
import static kr.lunaf.cloudislands.coreservice.config.CoreNetworkExposure.*;
import static kr.lunaf.cloudislands.coreservice.config.CoreSetupSummary.*;

import java.io.IOException;
import kr.lunaf.cloudislands.api.model.AddonStateBulkLoadRequest;
import kr.lunaf.cloudislands.api.model.AddonStateBulkSaveRequest;
import kr.lunaf.cloudislands.coreservice.IslandPlacement;
import kr.lunaf.cloudislands.coreservice.NodeRegistry;
import kr.lunaf.cloudislands.coreservice.addon.AddonStateRepository;
import kr.lunaf.cloudislands.coreservice.config.CoreServiceConfig;
import kr.lunaf.cloudislands.coreservice.http.CoreHttpResponses;
import kr.lunaf.cloudislands.coreservice.http.CoreRouteRegistry;
import kr.lunaf.cloudislands.coreservice.http.RouteGroup;
import kr.lunaf.cloudislands.protocol.node.NodeHeartbeatRequest;

public final class CoreConfigRoutes implements RouteGroup {
    private static final int MIN_NODE_PROTOCOL_VERSION = 1;
    private static final int MAX_NODE_PROTOCOL_VERSION = NodeHeartbeatRequest.CURRENT_PROTOCOL_VERSION;

    private final CoreServiceConfig config;
    private final NodeRegistry nodes;

    public CoreConfigRoutes(CoreServiceConfig config, NodeRegistry nodes) {
        this.config = config;
        this.nodes = nodes;
    }

    @Override
    public void register(CoreRouteRegistry registry) {
        registry.route("/v1/admin/config", this::config);
    }

    private void config(com.sun.net.httpserver.HttpExchange exchange) throws IOException {
        CoreHttpResponses.write(exchange, 200, configSummaryJson());
    }

    private static String storageBackendSafety(CoreServiceConfig config) {
        if (config == null || config.storageType() == null || config.storageType().isBlank()) {
            return "unknown-storage-backend";
        }
        if ("S3".equalsIgnoreCase(config.storageType())) {
            return "shared-object-storage-safe-for-multi-node-island-pools";
        }
        if ("LOCAL".equalsIgnoreCase(config.storageType())) {
            return "local-storage-requires-shared-filesystem-mount-for-multi-node-island-pools";
        }
        return "unsupported-storage-backend";
    }

    private String configSummaryJson() {
        kr.lunaf.cloudislands.storage.snapshot.SnapshotRetentionPolicy snapshotPolicy = config.snapshotRetentionPolicy().normalized();
        return "{"
            + "\"repositoryMode\":\"" + escape(config.repositoryMode()) + "\","
            + "\"jobQueueMode\":\"" + escape(config.jobQueueMode()) + "\","
            + "\"eventBusMode\":\"" + escape(config.eventBusMode()) + "\","
            + "\"effectiveRepositoryMode\":\"" + (config.jdbcRepositories() ? "JDBC" : "IN_MEMORY") + "\","
            + "\"effectiveJobQueueMode\":\"" + (config.jdbcJobs() ? "JDBC" : config.redisJobs() ? "REDIS" : "IN_MEMORY") + "\","
            + "\"effectiveEventBusMode\":\"" + (config.redisEvents() ? "REDIS" : "IN_MEMORY") + "\","
            + "\"coreJdbcRepositoriesEnabled\":" + config.jdbcRepositories() + ","
            + "\"coreJdbcJobsEnabled\":" + config.jdbcJobs() + ","
            + "\"configuredDatabaseType\":\"" + escape(config.configuredDatabaseType()) + "\","
            + "\"configuredDatabaseTypeSource\":\"" + escape(CoreServiceConfig.configuredDatabaseTypeSource()) + "\","
            + "\"runtimeMode\":\"" + escape(config.runtimeMode()) + "\","
            + "\"databaseBackend\":\"" + escape(jdbcBackend(config.jdbcUrl())) + "\","
            + "\"jdbcUrlSource\":\"" + escape(CoreServiceConfig.configuredJdbcUrlSource()) + "\","
            + "\"effectiveJdbcSettingsType\":\"" + escape(CoreServiceConfig.configuredJdbcSettingsType()) + "\","
            + "\"effectiveJdbcSettingsSource\":\"" + escape(CoreServiceConfig.configuredJdbcSettingsSource()) + "\","
            + "\"coreJdbcSupported\":" + coreJdbcSupported(config.jdbcUrl()) + ","
            + "\"coreJdbcSupportedBackends\":\"POSTGRESQL,MYSQL,MARIADB\","
            + "\"coreSetupFallbackBackends\":\"POSTGRESQL,MYSQL,MARIADB,CORE_API,UNSUPPORTED_JDBC\","
            + "\"coreSetupFallbackRequireSharedBeforeLocal\":" + config.setupDatabaseFallbackRequireSharedBeforeLocal() + ","
            + "\"coreSetupFallbackLocalLast\":" + config.setupDatabaseFallbackLocalLast() + ","
            + "\"coreSetupFallbackProductionSafeOrder\":\"" + escape(config.setupDatabaseFallbackProductionSafeOrder()) + "\","
            + "\"coreSetupDatabaseAutoSchema\":" + config.setupDatabaseAutoSchema() + ","
            + "\"coreSetupDatabaseAutoSchemaPolicy\":\"explicit-opt-in-postgresql-mysql-mariadb-bootstrap\","
            + "\"coreSetupDatabaseAutoSchemaResource\":\"postgresql=/db/migration/V1..V54,mysql-mariadb=/db/mysql/V1__cloudislands_mysql_schema.sql\","
            + "\"coreSetupDatabaseAutoSchemaHistoryTable\":\"cloudislands_schema_bootstrap\","
            + "\"coreSetupDatabaseAutoSchemaRetryPolicy\":\"ignore-existing-schema-objects-and-mark-bootstrap-after-complete-apply\","
            + "\"coreSetupDatabaseAutoSchemaGuardPolicy\":\"generated-columns-enforce-active-unique-guards-for-mysql-mariadb\","
            + "\"coreSetupFallbackEnabled\":" + config.setupDatabaseFallbackEnabled() + ","
            + "\"coreSetupAllowInMemoryFallback\":" + config.setupDatabaseAllowInMemoryFallback() + ","
            + "\"coreSetupFallbackEffective\":" + coreJdbcFallbackActive(config) + ","
            + "\"coreSetupFallbackSafetyForced\":" + coreSetupFallbackSafetyForced(config) + ","
            + "\"coreSetupFallbackPolicy\":\"" + escape(coreSetupFallbackPolicy(config)) + "\","
            + "\"coreSetupFallbackOrder\":\"" + escape(config.setupDatabaseFallbackOrder()) + "\","
            + "\"coreSetupFallbackMode\":\"" + escape(coreSetupFallbackMode(config)) + "\","
            + "\"coreSetupDatabaseRequestedBackend\":\"" + escape(config.setupDatabaseRequestedBackend()) + "\","
            + "\"coreSetupDatabaseEffectiveAuthority\":\"" + escape(config.setupDatabaseEffectiveAuthority()) + "\","
            + "\"coreSetupDatabaseEffectiveBackend\":\"" + escape(config.setupDatabaseEffectiveBackend()) + "\","
            + "\"coreSetupDatabaseFallbackTarget\":\"" + escape(config.setupDatabaseFallbackTarget()) + "\","
            + "\"coreSetupDatabasePostgresqlFallbackConfigured\":" + config.setupDatabasePostgresqlFallbackConfigured() + ","
            + "\"coreSetupDatabaseMysqlFallbackConfigured\":" + config.setupDatabaseMysqlFallbackConfigured() + ","
            + "\"coreSetupDatabaseMariadbFallbackConfigured\":" + config.setupDatabaseMariadbFallbackConfigured() + ","
            + "\"coreSetupDatabaseCoreApiFallbackConfigured\":" + config.setupDatabaseCoreApiFallbackConfigured() + ","
            + "\"coreSetupDatabaseFallbackReason\":\"" + escape(config.setupDatabaseFallbackReason()) + "\","
            + "\"coreSetupDatabaseFallbackSummary\":\"" + escape(config.setupDatabaseFallbackSummary()) + "\","
            + "\"coreSetupDatabaseFallbackCandidateChain\":\"" + escape(coreSetupFallbackCandidateChain(config)) + "\","
            + "\"coreSetupDatabaseFallbackReadyBackends\":\"" + escape(coreSetupFallbackReadyBackends(config)) + "\","
            + "\"coreSetupDatabaseFallbackMissingBackends\":\"" + escape(coreSetupFallbackMissingBackends(config)) + "\","
            + "\"coreSetupDatabaseFallbackDecision\":\"" + escape(coreSetupFallbackDecision(config)) + "\","
            + "\"coreSetupDatabaseDurable\":" + config.setupDatabaseDurable() + ","
            + "\"coreSetupDatabaseProductionDurable\":" + config.setupDatabaseProductionDurable() + ","
            + "\"coreSetupDatabaseReady\":" + config.setupDatabaseReady() + ","
            + "\"coreSetupDatabaseFallbackSafetyForced\":" + config.setupDatabaseFallbackSafetyForced() + ","
            + "\"coreSetupDatabaseFallbackSafetyMode\":\"" + escape(config.setupDatabaseFallbackSafetyMode()) + "\","
            + "\"coreSetupDatabaseOperationalModes\":\"POSTGRESQL=CORE_JDBC,MYSQL=CORE_JDBC,MARIADB=CORE_JDBC,CORE_API=CLIENT_MODE_NO_CORE_SERVICE_SELF_STORAGE\","
            + "\"coreSetupDatabasePrimaryAuthority\":\"POSTGRESQL_MYSQL_MARIADB_FOR_CORE_STATE_CORE_API_FOR_CLIENT_ADDON_STATE\","
            + "\"coreSetupDatabaseMysqlPolicy\":\"native-core-jdbc-through-setup.database.mysql-or-jdbc-url\","
            + "\"coreSetupDatabaseMariadbPolicy\":\"native-core-jdbc-through-setup.database.mariadb-or-jdbc-url\","
            + "\"coreSetupDatabaseCoreApiPolicy\":\"client-addon-state-marker-core-self-storage-requires-durable-jdbc-or-explicit-non-production-in-memory-fallback\","
            + "\"coreSetupDatabaseSafeFallbackWarning\":\"IN_MEMORY_CORE_FALLBACK_IS_NON_DURABLE_AND_NOT_READY_FOR_PRODUCTION\","
            + "\"coreSetupDatabaseConfigLoader\":\"yaml-nested-dotted-path\","
            + "\"coreSetupDatabaseResolvedPathExamples\":\"setup.database.type,setup.database.postgresql.jdbc-url,setup.database.postgresql.username,setup.database.mysql.host,setup.database.mysql.password,setup.database.mariadb.pool-size,setup.database.core-api.enabled\","
            + "\"coreSetupDatabaseConfigShapes\":\"setup.database.*,setup.database-*,setup.database.fallback.order(list-or-comma-string)\","
            + "\"coreSetupDatabaseTypedShapes\":\"setup.database.postgresql.*,setup.database.mysql.*,setup.database.mariadb.*,setup.database.core-api.*\","
            + "\"coreSetupDatabaseTypedCredentialKeys\":\"username,password,pool-size\","
            + "\"coreSetupDatabaseTypedHostMode\":\"requires-type-or-typed-url-inference\","
            + "\"coreSetupDatabaseTypedProbeOrder\":\"postgresql,mysql,mariadb\","
            + "\"coreSetupDatabaseCoreApiMode\":\"enabled-marker-no-core-jdbc\","
            + "\"coreSetupDatabaseCoreApiBaseUrl\":\"" + escape(config.setupDatabaseCoreApiBaseUrl()) + "\","
            + "\"coreSetupDatabaseCoreApiAuthTokenConfigured\":" + config.setupDatabaseCoreApiAuthTokenConfigured() + ","
            + "\"coreSetupDatabaseCoreApiAdminTokenConfigured\":" + config.setupDatabaseCoreApiAdminTokenConfigured() + ","
            + "\"coreSetupDatabaseCoreApiTimeoutMs\":" + config.setupDatabaseCoreApiTimeoutMillis() + ","
            + "\"coreSetupDatabaseCoreApiClientMode\":" + config.setupDatabaseCoreApiClientMode() + ","
            + "\"coreSetupDatabaseCoreApiClientReady\":" + config.setupDatabaseCoreApiClientReady() + ","
            + "\"coreSetupDatabaseFallbackReadiness\":\"" + escape(config.setupDatabaseFallbackReadiness()) + "\","
            + "\"coreSetupDatabaseCoreApiConfigPaths\":\"setup.database.core-api.base-url,setup.database.core-api.url,setup.database.core-api.auth-token,setup.database.core-api.admin-token,setup.database.core-api.timeout-ms,setup.core-api.*,setup-core-api.*,core-api.*\","
            + "\"coreSetupDatabaseEnv\":\"CI_DATABASE_TYPE,CI_JDBC_URL,CI_DB_USERNAME,CI_DB_PASSWORD,CI_DB_POOL_SIZE,CI_DB_AUTO_SCHEMA,CI_DB_FALLBACK_ENABLED,CI_DB_FALLBACK_ORDER,CI_SETUP_CORE_API_BASE_URL,CI_SETUP_CORE_API_AUTH_TOKEN,CI_SETUP_CORE_API_ADMIN_TOKEN,CI_SETUP_CORE_API_TIMEOUT_MS\","
            + "\"coreSetupDatabasePrecedence\":\"env,nested-setup-database,legacy-flat-setup,database-default\","
            + "\"coreSetupDatabaseNameAliases\":\"setup.database.name,setup.database.database,setup.database-name\","
            + "\"nodeAllocatorPolicy\":\"pool-filter-unique-velocity-server-fresh-heartbeat-storage-ready-template-version-capacity-then-weighted-score\","
            + "\"nodeAllocatorScoreWeights\":\"players=0.25,activeIslands=0.15,mspt=0.25,activationQueue=0.15,chunkLoad=0.10,memory=0.05,recentFailure=0.05\","
            + "\"nodeAllocatorHardRules\":\"READY-or-policy-allowed-SOFT_FULL,heartbeat-fresh,storage-available,hard-player-cap,max-active-islands,max-activation-queue,template-supported,min-node-version,unique-velocity-server-name,non-default-node-identity\","
            + "\"nodeAllocatorFiveSixNodePolicy\":\"no-fixed-node-count-limit-add-island-nodes-with-unique-node-id-unique-velocity-server-name-shared-storage\","
            + "\"coreSetupDatabaseJdbcAliases\":\"CI_JDBC_URL,setup.database.jdbc-url,setup.jdbc-url,database.jdbc-url\","
            + "\"coreSetupDatabaseTypeInference\":\"CI_DATABASE_TYPE,setup.database.type,setup.database-type,setup.database.core-api.enabled,CI_JDBC_URL,setup.database.jdbc-url,setup.jdbc-url,setup.database.postgresql.jdbc-url,setup.database.postgresql.url,setup.database.mysql.jdbc-url,setup.database.mysql.url,setup.database.mariadb.jdbc-url,setup.database.mariadb.url,typed-host-name,database.jdbc-url\","
            + "\"observabilityMetricsPolicy\":\"prometheus-exporter-covers-node-island-route-permission-job-storage-database-redis-metrics\","
            + "\"observabilityRequiredMetrics\":\"cloudislands_nodes_online,cloudislands_node_players,cloudislands_node_mspt,cloudislands_node_active_islands,cloudislands_node_activation_queue,cloudislands_island_activation_seconds,cloudislands_island_save_seconds,cloudislands_island_snapshot_seconds,cloudislands_route_ticket_created_total,cloudislands_route_ticket_failed_total,cloudislands_permission_checks_total,cloudislands_permission_cache_hit_ratio,cloudislands_jobs_pending,cloudislands_jobs_failed_total,cloudislands_jobs_retry_total,cloudislands_storage_upload_seconds,cloudislands_storage_download_seconds,cloudislands_database_query_seconds,cloudislands_redis_latency_seconds\","
            + "\"observabilityRequiredDashboardPanels\":\"nodes-online,node-players,node-mspt,active-islands,activation-seconds,island-save-failures,route-failures,redis-latency,database-pool-usage,object-storage-failure-ratio\","
            + "\"observabilityDashboardPolicy\":\"grafana-dashboard-must-show-node-load-activation-save-route-redis-db-and-object-storage-health\","
            + "\"coreJdbcFallbackReason\":\"" + escape(coreJdbcFallbackReason(config)) + "\","
            + "\"coreJdbcFallbackActive\":" + coreJdbcFallbackActive(config) + ","
            + "\"coreJdbcFallbackStatus\":\"" + escape(coreJdbcFallbackStatus(config)) + "\","
            + "\"addonStateBulkSaveApi\":true,"
            + "\"addonStateBulkSaveGlobalEndpoint\":\"" + AddonStateBulkSaveRequest.GLOBAL_LEGACY_ENDPOINT + "\","
            + "\"addonStateBulkSaveIslandEndpoint\":\"" + AddonStateBulkSaveRequest.ISLAND_LEGACY_ENDPOINT + "\","
            + "\"addonStateTableKeyValueBulkSaveGlobalEndpoint\":\"" + AddonStateBulkSaveRequest.GLOBAL_ENDPOINT + "\","
            + "\"addonStateTableKeyValueBulkSaveIslandEndpoint\":\"" + AddonStateBulkSaveRequest.ISLAND_ENDPOINT + "\","
            + "\"addonStateTableKeyValueBulkSaveGlobalAlias\":\"" + AddonStateBulkSaveRequest.GLOBAL_BULK_SAVE_ALIAS + "\","
            + "\"addonStateTableKeyValueBulkSaveIslandAlias\":\"" + AddonStateBulkSaveRequest.ISLAND_BULK_SAVE_ALIAS + "\","
            + "\"addonStateTableKeyValueBulkGlobalEndpoint\":\"" + AddonStateBulkSaveRequest.GLOBAL_BULK_ALIAS + "\","
            + "\"addonStateTableKeyValueBulkIslandEndpoint\":\"" + AddonStateBulkSaveRequest.ISLAND_BULK_ALIAS + "\","
            + "\"addonStateTableKeyValueBulkSaveGlobalAliases\":\"" + String.join(",", AddonStateBulkSaveRequest.GLOBAL_ENDPOINTS) + "\","
            + "\"addonStateTableKeyValueBulkSaveIslandAliases\":\"" + String.join(",", AddonStateBulkSaveRequest.ISLAND_ENDPOINTS) + "\","
            + "\"addonStateTableKeyValueBulkLoadGlobalEndpoint\":\"" + AddonStateBulkLoadRequest.GLOBAL_ENDPOINT + "\","
            + "\"addonStateTableKeyValueBulkLoadIslandEndpoint\":\"" + AddonStateBulkLoadRequest.ISLAND_ENDPOINT + "\","
            + "\"addonStateTableKeyValueBulkLoadGlobalAliases\":\"" + String.join(",", AddonStateBulkLoadRequest.GLOBAL_ENDPOINTS) + "\","
            + "\"addonStateTableKeyValueBulkLoadIslandAliases\":\"" + String.join(",", AddonStateBulkLoadRequest.ISLAND_ENDPOINTS) + "\","
            + "\"addonStateTableLoadGlobalEndpoint\":\"" + AddonStateBulkLoadRequest.GLOBAL_TABLE_LOAD_ALIAS + "\","
            + "\"addonStateTableLoadIslandEndpoint\":\"" + AddonStateBulkLoadRequest.ISLAND_TABLE_LOAD_ALIAS + "\","
            + "\"addonStateTableBulkGlobalEndpoint\":\"" + AddonStateBulkSaveRequest.GLOBAL_TABLE_BULK_ENDPOINT + "\","
            + "\"addonStateTableBulkIslandEndpoint\":\"" + AddonStateBulkSaveRequest.ISLAND_TABLE_BULK_ENDPOINT + "\","
            + "\"addonStateTableBulkSetGlobalEndpoint\":\"" + AddonStateBulkSaveRequest.GLOBAL_TABLE_BULK_SET_ENDPOINT + "\","
            + "\"addonStateTableBulkSetIslandEndpoint\":\"" + AddonStateBulkSaveRequest.ISLAND_TABLE_BULK_SET_ENDPOINT + "\","
            + "\"addonStateTableKeyValueBulkSavePayload\":\"addonId,islandId(optional),values,tables\","
            + "\"addonStateTableKeyValueBulkLoadPayload\":\"addonId,islandId(optional),table\","
            + "\"addonStateTableKeyValueBulkSaveStorageMode\":\"table-prefix-flattened-key-value\","
            + "\"addonStateTableKeyValueBulkSaveRepositoryApi\":\"AddonStateRepository.tableKeyValueBulkSave,AddonStateRepository.tableKeyValueBulkSaveIsland,AddonStateRepository.tableBulk,AddonStateRepository.tableBulkIsland,AddonStateRepository.tableKeyValueBulkLoad,AddonStateRepository.tableKeyValueBulkLoadIsland,AddonStateBulkSaveRequest,AddonStateBulkLoadRequest,IslandAddonService.tableBulkState,IslandAddonService.tableBulkIslandState,IslandAddonService.tableKeyValueBulkSaveState,IslandAddonService.tableKeyValueBulkSaveIslandState,IslandAddonService.tableKeyValueBulkLoadState,IslandAddonService.tableKeyValueBulkLoadIslandState,IslandAddonService.tableLoadState,IslandAddonService.tableLoadIslandState,CoreApiClient.tableKeyValueBulkSaveAddonState,CoreApiClient.tableKeyValueBulkSaveAddonIslandState,CoreApiClient.tableBulkAddonState,CoreApiClient.tableBulkAddonIslandState,CoreApiClient.tableKeyValueBulkLoadAddonState,CoreApiClient.tableKeyValueBulkLoadAddonIslandState,CoreApiClient.tableLoadAddonState,CoreApiClient.tableLoadAddonIslandState\","
            + "\"addonStateTableKeyPrefix\":\"" + AddonStateRepository.TABLE_STATE_KEY_SHAPE + "\","
            + "\"addonStateMaxAddonIdLength\":" + AddonStateRepository.MAX_ADDON_ID_LENGTH + ","
            + "\"addonStateMaxKeyLength\":" + AddonStateRepository.MAX_KEY_LENGTH + ","
            + "\"addonStateMaxValueLength\":" + AddonStateRepository.MAX_VALUE_LENGTH + ","
            + "\"addonStateMaxKeysPerAddon\":" + AddonStateRepository.MAX_KEYS_PER_ADDON + ","
            + "\"addonStateTableKeyValueBulkSaveFallback\":\"local-cache-on-core-api-failure\","
            + "\"addonStateTableKeyValueBulkLoadFallback\":\"local-cache-or-empty-table-on-core-api-failure\","
            + "\"databasePoolSize\":" + config.databasePoolSize() + ","
            + "\"storageType\":\"" + escape(config.storageType()) + "\","
            + "\"storageSharedBackend\":" + ("S3".equalsIgnoreCase(config.storageType())) + ","
            + "\"storageMultiNodeSafe\":" + ("S3".equalsIgnoreCase(config.storageType())) + ","
            + "\"storageBackendSafety\":\"" + escape(storageBackendSafety(config)) + "\","
            + "\"storageLocalMultiNodePolicy\":\"LOCAL requires the same shared filesystem mount on every Island node; otherwise use S3 or MinIO\","
            + "\"storageS3MultiNodePolicy\":\"S3 or MinIO is the recommended shared object storage for 5/6 Island node pools\","
            + "\"storageLayout\":\"islands/{islandUuid}/manifest.json,latest,snapshots/{snapshotNo}/bundle.tar.zst,checksums.sha256,backups,recovery\","
            + "\"storageLatestPointer\":\"islands/{islandUuid}/latest\","
            + "\"storageSnapshotManifest\":\"islands/{islandUuid}/snapshots/{snapshotNo}/manifest.json\","
            + "\"storageBundleObject\":\"islands/{islandUuid}/snapshots/{snapshotNo}/bundle.tar.zst\","
            + "\"storageChecksumFile\":\"islands/{islandUuid}/snapshots/{snapshotNo}/checksums.sha256\","
            + "\"storageDeleteBackupPath\":\"islands/{islandUuid}/backups/delete-{snapshotNo}\","
            + "\"storageRecoveryPath\":\"islands/{islandUuid}/recovery\","
            + "\"storagePortabilityPolicy\":\"bundle-and-manifest-are-island-uuid-scoped-node-independent\","
            + "\"storageRestoreManifestRequired\":true,"
            + "\"storageRestoreChecksumPolicy\":\"verify-manifest-checksum-for-latest-snapshot-and-storage-path\","
            + "\"storageRestorePortableRequired\":true,"
            + "\"storageRestoreSupportedFormats\":\"checksum=SHA-256,compression=zstd\","
            + "\"failureHandlingNodeDownPolicy\":\"heartbeat-timeout>node-down>block-new-routes>mark-active-islands-recovery-required>fallback-players-lobby>snapshot-check>recover-on-other-node-or-quarantine\","
            + "\"failureHandlingRecoveryRequiredPolicy\":\"" + kr.lunaf.cloudislands.common.runtime.IslandRuntimeStatePolicy.RECOVERY_REQUIRED_POLICY + "\","
            + "\"failureHandlingCoreApiDownAllowed\":\"active-island-play,local-cache-protection,basic-local-teleport-fallback\","
            + "\"failureHandlingCoreApiDownLimited\":\"new-island-create,inactive-island-activation,island-route,member-change,flag-change\","
            + "\"failureHandlingCoreApiDownPlayerMessage\":\"현재 섬 서비스 일부 기능이 점검 중입니다.\","
            + "\"failureHandlingRedisDownAllowed\":\"database-direct-read-degraded-mode-without-data-loss\","
            + "\"failureHandlingRedisDownLimited\":\"cache-performance,event-propagation,job-queue-processing,heartbeat-freshness\","
            + "\"failureHandlingRedisDownRecommendation\":\"run-redis-high-availability-in-production\","
            + "\"failureHandlingObjectStorageDownAllowed\":\"already-active-island-play-continues-on-node-local-world\","
            + "\"failureHandlingObjectStorageDownLimited\":\"new-activation,island-save,snapshot,recovery\","
            + "\"failureHandlingObjectStorageRetryPolicy\":\"queue-failed-save-and-snapshot-operations-for-retry-while-primary-storage-is-unavailable\","
            + "\"failureHandlingQuarantinePolicy\":\"" + kr.lunaf.cloudislands.common.runtime.IslandRuntimeStatePolicy.QUARANTINE_POLICY + "\","
            + "\"failureHandlingRecoveryStateSummary\":\"" + kr.lunaf.cloudislands.common.runtime.IslandRuntimeStatePolicy.recoveryStateSummary() + "\","
            + "\"islandResourceModel\":\"global-resource\","
            + "\"islandPortableBundle\":true,"
            + "\"islandServerPinned\":false,"
            + "\"islandExecutionModel\":\"dynamic-island-node-pool\","
            + "\"islandNodeRole\":\"runtime-execution-node-only\","
            + "\"islandRoutingModel\":\"route-ticket-to-active-or-best-node\","
            + "\"createIslandRequestFlow\":\"velocity-command>core-createIsland>db-transaction-lock>node-allocator>create-island-job>agent-claim>template-restore>cell-allocate>runtime-active>route-ticket-ready>velocity-connect>paper-consume-ticket>spawn-teleport\","
            + "\"createIslandDuplicateGuard\":\"redis-player-creation-lock-plus-jdbc-player-profile-for-update\","
            + "\"createIslandJdbcLockPolicy\":\"upsert-player-profile-select-for-update-then-owner-island-select-for-update\","
            + "\"createIslandTransactionScope\":\"islands-row-owner-member-runtime-primary-island\","
            + "\"createIslandJobPolicy\":\"commit-before-job-publish-error-state-on-job-queue-failure\","
            + "\"createIslandInitialTicketState\":\"PREPARING-until-paper-agent-completes-create-job\","
            + "\"homeRequestFlow\":\"velocity-command>core-createHomeRoute>runtime-check>active-or-activate-best-node>route-ticket-ready>velocity-connect>paper-teleport\","
            + "\"visitRequestFlow\":\"velocity-command>target-island-lookup>public-ban-permission-check>active-or-activate>visitor-ticket>velocity-connect>visitor-spawn-teleport\","
            + "\"routePlayerLoadingUi\":\"actionbar-and-bossbar-progress-without-node-name\","
            + "\"routePlayerFailureCodes\":\"" + escape(kr.lunaf.cloudislands.common.routing.RouteFailurePolicy.PUBLIC_FAILURE_CODES) + "\","
            + "\"routePlayerFailureMessages\":\"" + escape(kr.lunaf.cloudislands.common.routing.RouteFailurePolicy.publicMessageSummary()) + "\","
            + "\"routePublicMessagePolicy\":\"" + escape(kr.lunaf.cloudislands.common.routing.RouteFailurePolicy.PUBLIC_MESSAGE_POLICY) + "\","
            + "\"routeDebugReasonPolicy\":\"" + escape(kr.lunaf.cloudislands.common.routing.RouteFailurePolicy.DEBUG_REASON_POLICY) + "\","
            + "\"routeVisitRejectionPolicy\":\"" + escape(kr.lunaf.cloudislands.common.routing.RouteFailurePolicy.VISIT_REJECTION_POLICY) + "\","
            + "\"routeTransferFailurePolicy\":\"clear-ticket-session-and-show-public-message-or-return-lobby\","
            + "\"softFullRoutingPolicy\":\"new-and-inactive-islands-use-ready-node-active-owner-member-reserve-current-node-visitors-queue-or-limit\","
            + "\"newActivationSoftFullPolicy\":\"" + escape(config.softFullPolicy()) + "\","
            + "\"newActivationSoftFullAvoided\":" + avoidsSoftFullNewActivations(config.softFullPolicy()) + ","
            + "\"newActivationHardFullPolicy\":\"" + escape(config.hardFullPolicy()) + "\","
            + "\"newActivationHardFullAllowed\":" + allowsHardFullNewActivations(config.hardFullPolicy()) + ","
            + "\"softFullNewActivationBehavior\":\"ready-node-preferred-soft-full-avoided-unless-policy-allows\","
            + "\"softFullExistingRouteBehavior\":\"active-owner-member-routes-can-use-current-soft-full-node-visitors-queue-or-limit\","
            + "\"moduleLayout\":\"" + escape(kr.lunaf.cloudislands.common.packaging.CloudIslandsModuleLayoutPolicy.requiredModuleSummary()) + "\","
            + "\"coreModuleLayout\":\"" + escape(kr.lunaf.cloudislands.common.packaging.CloudIslandsModuleLayoutPolicy.requiredModuleSummary()) + "\","
            + "\"addonModuleLayout\":\"" + escape(kr.lunaf.cloudislands.common.packaging.CloudIslandsModuleLayoutPolicy.optionalExtensionModuleSummary()) + "\","
            + "\"moduleResponsibilityLayout\":\"" + escape(kr.lunaf.cloudislands.common.packaging.CloudIslandsModuleLayoutPolicy.moduleResponsibilitySummary()) + "\","
            + "\"moduleRuntimeSurfaceLayout\":\"" + escape(kr.lunaf.cloudislands.common.packaging.CloudIslandsModuleLayoutPolicy.moduleRuntimeSurfaceSummary()) + "\","
            + "\"distributionLayout\":\"" + escape(kr.lunaf.cloudislands.common.packaging.CloudIslandsModuleLayoutPolicy.distributionArtifactSummary()) + "\","
            + "\"distributionTaskLayout\":\"" + escape(kr.lunaf.cloudislands.common.packaging.CloudIslandsModuleLayoutPolicy.distributionTaskSummary()) + "\","
            + "\"distributionMarkdownPackagingGuard\":\"verifyMarkdownDocsExcludedFromArtifacts-before-build-and-distBundle\","
            + "\"productionReadinessContract\":\"" + escape(kr.lunaf.cloudislands.common.observability.ProductionReadinessPolicy.CONTRACT) + "\","
            + "\"productionReadinessGates\":\"" + escape(kr.lunaf.cloudislands.common.observability.ProductionReadinessPolicy.requiredGateSummary()) + "\","
            + "\"productionDeploymentTemplatePolicy\":\"" + escape(kr.lunaf.cloudislands.common.observability.ProductionReadinessPolicy.DEPLOYMENT_TEMPLATE_POLICY) + "\","
            + "\"productionRollingUpgradePolicy\":\"" + escape(kr.lunaf.cloudislands.common.observability.ProductionReadinessPolicy.ROLLING_UPGRADE_POLICY) + "\","
            + "\"productionE2ePolicy\":\"" + escape(kr.lunaf.cloudislands.common.observability.ProductionReadinessPolicy.E2E_POLICY) + "\","
            + "\"productionChaosPolicy\":\"" + escape(kr.lunaf.cloudislands.common.observability.ProductionReadinessPolicy.CHAOS_POLICY) + "\","
            + "\"productionBackupRestorePolicy\":\"" + escape(kr.lunaf.cloudislands.common.observability.ProductionReadinessPolicy.BACKUP_RESTORE_POLICY) + "\","
            + "\"productionSupportBundlePolicy\":\"" + escape(kr.lunaf.cloudislands.common.observability.ProductionReadinessPolicy.SUPPORT_BUNDLE_POLICY) + "\","
            + "\"integrationDistributedHookPolicy\":\"" + escape(kr.lunaf.cloudislands.common.integration.CloudIntegrationPolicy.DISTRIBUTED_HOOK_POLICY) + "\","
            + "\"integrationKnownPlugins\":\"" + escape(String.join(",", kr.lunaf.cloudislands.common.integration.CloudIntegrationPolicy.knownPlugins())) + "\","
            + "\"integrationCoreProtectPolicy\":\"" + escape(kr.lunaf.cloudislands.common.integration.CloudIntegrationPolicy.COREPROTECT_POLICY) + "\","
            + "\"integrationWorldEditPolicy\":\"" + escape(kr.lunaf.cloudislands.common.integration.CloudIntegrationPolicy.WORLDEDIT_POLICY) + "\","
            + "\"integrationCustomItemPolicy\":\"" + escape(kr.lunaf.cloudislands.common.integration.CloudIntegrationPolicy.CUSTOM_ITEM_POLICY) + "\","
            + "\"integrationStackerPolicy\":\"" + escape(kr.lunaf.cloudislands.common.integration.CloudIntegrationPolicy.STACKER_POLICY) + "\","
            + "\"integrationPermissionPolicy\":\"" + escape(kr.lunaf.cloudislands.common.integration.CloudIntegrationPolicy.PERMISSION_POLICY) + "\","
            + "\"integrationActivityPolicy\":\"" + escape(kr.lunaf.cloudislands.common.integration.CloudIntegrationPolicy.ACTIVITY_POLICY) + "\","
            + "\"integrationEconomyPolicy\":\"" + escape(kr.lunaf.cloudislands.common.integration.CloudIntegrationPolicy.ECONOMY_POLICY) + "\","
            + "\"addonRegistryPolicy\":\"paper-addon-registers-core-stores-snapshot-only\","
            + "\"addonStateOwnershipPolicy\":\"core-persists-addon-key-value-state-without-addon-business-logic\","
            + "\"addonRemovalSafetyPolicy\":\"missing-addon-metadata-or-state-must-not-block-island-lifecycle\","
            + "\"addonStateFailureIsolationPolicy\":\"addon-state-storage-outages-return-503-without-affecting-island-lifecycle\","
            + "\"addonExtensionModel\":\"optional-external-plugin-using-cloudislands-api\","
            + "\"addonApiLookupPolicy\":\"cloudislands-provider-first-bukkit-servicesmanager-fallback\","
            + "\"addonApiContractVersion\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.CONTRACT_VERSION) + "\","
            + "\"addonApiContractCompatibility\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.metadataCompatibilityStatus(kr.lunaf.cloudislands.api.CloudIslandsApiContract.metadata())) + "\","
            + "\"addonApiContractCompatible\":" + kr.lunaf.cloudislands.api.CloudIslandsApiContract.compatibleMetadata(kr.lunaf.cloudislands.api.CloudIslandsApiContract.metadata()) + ","
            + "\"addonApiRequiredMetadataKeys\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.requiredMetadataKeysCsv()) + "\","
            + "\"addonApiReadPolicy\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.READ_POLICY) + "\","
            + "\"addonApiWriteAuthority\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.WRITE_AUTHORITY) + "\","
            + "\"addonApiSyncEventPolicy\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.SYNC_EVENT_POLICY) + "\","
            + "\"addonApiStoragePolicy\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.ADDON_STORAGE_POLICY) + "\","
            + "\"addonApiRemovalPolicy\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.ADDON_REMOVAL_POLICY) + "\","
            + "\"addonApiReconnectPolicy\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.ADDON_RECONNECT_POLICY) + "\","
            + "\"addonJavaPluginApiPolicy\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.JAVA_PLUGIN_API_POLICY) + "\","
            + "\"addonInternalApiPolicy\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.INTERNAL_API_POLICY) + "\","
            + "\"addonEventApiPolicy\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.EVENT_API_POLICY) + "\","
            + "\"addonTimeoutRetryPolicy\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.TIMEOUT_RETRY_POLICY) + "\","
            + "\"addonCompatibilityTestkitPolicy\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.COMPATIBILITY_TESTKIT_POLICY) + "\","
            + "\"addonCoreAuthPolicy\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.CORE_AUTH_POLICY) + "\","
            + "\"addonAdminEndpointPolicy\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.ADMIN_ENDPOINT_POLICY) + "\","
            + "\"addonNetworkExposurePolicy\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.NETWORK_EXPOSURE_POLICY) + "\","
            + "\"addonSecurityPostureSummary\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.SECURITY_POSTURE_SUMMARY) + "\","
            + "\"addonTopologyPrivacyPolicy\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.TOPOLOGY_PRIVACY_POLICY) + "\","
            + "\"addonConsistencyAuthorityPolicy\":\"" + escape(kr.lunaf.cloudislands.api.CloudIslandsApiContract.CONSISTENCY_AUTHORITY_POLICY) + "\","
            + "\"addonEventDeliveryPolicy\":\"core-global-events-to-paper-poller-to-cloudislands-addon-and-bukkit-events\","
            + "\"addonEventCoverage\":\"pre-create,create,pre-activate,activate,deactivate,migrate,delete,delete-backup-failed,restore,reset,recovery,runtime,pre-visit,visit,invite,member-join,member-left,member-role,member-change,ownership,rename,access,visitor-ban,visitor-kick,flag,permission-check,permission-change,role-catalog,biome,home,warp-create,warp-delete,warp-change,bank,chat,mission,blocks,block-value,level,worth,upgrade,limit,snapshot,template,addon-state,node,core-cache,core-reload,route-ticket\","
            + "\"addonEventBackfillPolicy\":\"paper-poller-uses-listEventsSince-with-sequence-gap-cache-invalidation\","
            + "\"satisPackaging\":\"official-external-addon\","
            + "\"satisCoreCoupling\":\"optional-addon-no-core-runtime-dependency\","
            + "\"satisAddonRemovalPolicy\":\"core-boots-and-islands-load-without-satis-jar\","
            + "\"satisDataRetentionPolicy\":\"addon-state-preserved-when-disabled-or-removed\","
            + "\"satisCoreBootRequiresAddon\":false,"
            + "\"satisCommandOwner\":\"optional-satis-paper-addon\","
            + "\"satisCrossNodeStatePolicy\":\"addon-state-must-be-stored-in-core-api-or-shared-database-not-paper-node-memory\","
            + "\"satisIslandMovePolicy\":\"when-island-moves-between-island-nodes-addon-remaps-state-to-current-active-world-and-cell\","
            + "\"satisFeatureDisablePolicy\":\"disabled-features-register-no-commands-gui-listeners-tasks-or-data-writes-and-preserve-existing-data\","
            + "\"satisSuperiorSkyblock2Policy\":\"no-runtime-dependency-use-cloudislands-public-api-and-addon-spi-only\","
            + "\"satisOperationScenarios\":\"" + escape(kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.operationScenarioSummary()) + "\","
            + "\"satisRecommendedModeReasons\":\"" + escape(kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.recommendedModeReasonSummary()) + "\","
            + "\"satisComponentBoundaries\":\"" + escape(kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.componentBoundarySummary()) + "\","
            + "\"satisFeatureOffRuntimeBlocks\":\"" + escape(kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.featureOffRuntimeBlockSummary()) + "\","
            + "\"satisStateStorageConfig\":\"" + escape(kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.stateStorageConfigSummary()) + "\","
            + "\"satisPlayerExperiencePolicy\":\"" + escape(kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.playerExperienceBoundarySummary()) + "\","
            + "\"satisOfficialFeaturePackPolicy\":\"" + escape(kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.officialFeaturePackBoundarySummary()) + "\","
            + "\"satisNodeMoveRemapFlow\":\"" + escape(kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.nodeMoveRemapStepSummary()) + "\","
            + "\"satisFailureRecoveryFlow\":\"" + escape(kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.failureRecoveryStepSummary()) + "\","
            + "\"satisAddonReconnectFlow\":\"" + escape(kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.addonReconnectStepSummary()) + "\","
            + "\"satisCompletionCriteria\":\"" + escape(kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.completionCriteriaSummary()) + "\","
            + "\"satisRecoveryPolicy\":\"use-last-confirmed-addon-state-after-node-failure-and-avoid-duplicate-ticks-with-core-fencing\","
            + "\"satisAddonAbsentPolicy\":\"cloudislands-core-and-island-lifecycle-do-not-require-cloudislands-satis-installed\","
            + "\"satisDisabledRuntimePolicy\":\"disabled-satis-keeps-core-create-route-protect-save-restore-working-without-registering-satis-runtime-components\","
            + "\"satisReinstallPolicy\":\"preserved-addon-state-can-be-reconnected-when-satis-addon-is-installed-again\","
            + "\"satisStateAuthorityPolicy\":\"portable-addon-state-is-authoritative-in-core-api-bulk-table-key-value-or-configured-shared-database\","
            + "\"satisMultiNodeSafe\":true,"
            + "\"satisNodeCountPolicy\":\"island-node-count-does-not-change-satis-state-identity-or-storage-authority\","
            + "\"velocitySatisCommandPolicy\":\"no-direct-satis-command-handler-route-only\","
            + "\"paperSatisCommandPolicy\":\"addon-registers-own-commands-when-enabled\","
            + "\"finalRequestFlowKeys\":\"" + kr.lunaf.cloudislands.common.routing.FinalRequestFlowPolicy.flowKeys() + "\","
            + "\"finalRequestFlowIslandCreate\":\"" + kr.lunaf.cloudislands.common.routing.FinalRequestFlowPolicy.flowSummary("island-create") + "\","
            + "\"finalRequestFlowIslandHome\":\"" + kr.lunaf.cloudislands.common.routing.FinalRequestFlowPolicy.flowSummary("island-home") + "\","
            + "\"finalRequestFlowIslandVisit\":\"" + kr.lunaf.cloudislands.common.routing.FinalRequestFlowPolicy.flowSummary("island-visit") + "\","
            + "\"finalRequestFlowSoftFullRouting\":\"" + kr.lunaf.cloudislands.common.routing.FinalRequestFlowPolicy.flowSummary("soft-full-routing") + "\","
            + "\"islandPool\":\"" + escape(config.islandPool()) + "\","
            + "\"islandPoolNodeCount\":" + islandPoolNodeCount(config, nodes) + ","
            + "\"islandPoolRouteCandidateCount\":" + islandPoolRouteCandidateCount(config, nodes) + ","
            + "\"islandPoolRouteCandidateRecommendedMinimum\":" + islandPoolRouteCandidateRecommendedMinimum(config, nodes) + ","
            + "\"islandPoolRouteCandidateMinimumStatus\":\"" + escape(islandPoolRouteCandidateMinimumStatus(config, nodes)) + "\","
            + "\"islandPoolRouteCandidateNodeIds\":\"" + escape(islandPoolRouteCandidateNodeIds(config, nodes)) + "\","
            + "\"islandPoolScaleStatus\":\"" + escape(islandPoolScaleStatus(config, nodes)) + "\","
            + "\"islandPoolScaleModel\":\"dynamic-node-pool-by-node-id\","
            + "\"islandPoolElasticLimitPolicy\":\"" + kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.SCALE_POLICY + "\","
            + "\"islandPoolScaleGuidance\":\"add-island-nodes-with-unique-node-id-unique-velocity-server-name-shared-storage\","
            + "\"islandPoolHorizontalScalePolicy\":\"no-hardcoded-island-node-count-unique-node-id-unique-velocity-server-name-shared-storage-required\","
            + "\"islandPoolFiveSixNodePolicy\":\"" + kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.FIVE_SIX_NODE_POLICY + "\","
            + "\"islandPoolScaleReadinessPolicy\":\"" + kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.SCALE_READINESS_POLICY + "\","
            + "\"islandPoolScaleReadinessSummary\":\"" + kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.scaleReadinessSummary() + "\","
            + "\"islandPoolFiveSixNodeHealthy\":" + islandPoolFiveSixNodeHealthy(config, nodes) + ","
            + "\"islandPoolFiveSixNodeStatus\":\"" + escape(islandPoolFiveSixNodeStatus(config, nodes)) + "\","
            + "\"islandPlacementPolicy\":\"deterministic-uuid-shard-cell\","
            + "\"islandPlacementShardCount\":" + IslandPlacement.SHARD_COUNT + ","
            + "\"islandPlacementCellsPerAxis\":" + IslandPlacement.CELLS_PER_AXIS + ","
            + "\"islandPlacementCollisionPolicy\":\"uuid-derived-cell-with-runtime-occupied-cell-probing-db-unique-guard-fencing-and-node-lease\","
            + "\"islandNodeHardRules\":\"pool-match,ready-or-soft-full,fresh-heartbeat,hard-cap-open,activation-queue-open,object-storage-available,template-supported,min-node-version,not-default-identity\","
            + "\"islandNodeScoreWeights\":\"players=0.25,activeIslands=0.15,mspt=0.25,activationQueue=0.15,chunkLoad=0.10,memory=0.05,recentFailure=0.05\","
            + "\"islandNodeSchemaColumns\":\"id,pool,velocity_server_name,node_version,state,soft_player_cap,hard_player_cap,reserved_slots,max_active_islands,players,active_islands,mspt,heap_used_mb,heap_max_mb,activation_queue,max_activation_queue,chunk_load_pressure,recent_failure_penalty,object_storage_available,supported_templates,last_heartbeat\","
            + "\"islandNodeExistingRoutePolicy\":\"active-island-stays-on-current-node-unless-node-missing-stale-down-or-admin-migration\","
            + "\"islandNodeVisitorSoftFullPolicy\":\"visitors-queue-or-retry-on-soft-full-active-node-members-use-reserved-slots\","
            + "\"redisRolePolicy\":\"" + escape(kr.lunaf.cloudislands.common.cache.CacheStrategyPolicy.REDIS_ROLE) + "\","
            + "\"redisKeyScope\":\"" + escape(kr.lunaf.cloudislands.common.cache.CacheStrategyPolicy.REDIS_KEY_SCOPE) + "\","
            + "\"redisTtlSummary\":\"" + escape(kr.lunaf.cloudislands.common.cache.CacheStrategyPolicy.REDIS_TTL_SUMMARY) + "\","
            + "\"redisConsistencyGuard\":\"" + escape(kr.lunaf.cloudislands.common.cache.CacheStrategyPolicy.CONSISTENCY_GUARD) + "\","
            + "\"fencingWritePolicy\":\"" + escape(kr.lunaf.cloudislands.common.security.FencingToken.WRITE_POLICY) + "\","
            + "\"fencingRedisLockPolicy\":\"" + escape(kr.lunaf.cloudislands.common.security.FencingToken.REDIS_LOCK_POLICY) + "\","
            + "\"nodeProtocolMinSupported\":" + MIN_NODE_PROTOCOL_VERSION + ","
            + "\"nodeProtocolCurrent\":" + MAX_NODE_PROTOCOL_VERSION + ","
            + "\"nodeProtocolNegotiationPolicy\":\"" + kr.lunaf.cloudislands.protocol.ProtocolVersion.NEGOTIATION_POLICY + "\","
            + "\"nodeProtocolHeartbeatField\":\"" + kr.lunaf.cloudislands.protocol.ProtocolVersion.HEARTBEAT_FIELD + "\","
            + "\"routingFailureDetailKeys\":\"pool,nodeCount,readyOrSoftFullNodeCount,storageReadyNodeCount,primaryStorageHealthyNodeCount,storageSaveRetryBacklogNodeCount,storageSaveRetryBacklogTotal,hardCapOpenNodeCount,activeIslandOpenNodeCount,queueOpenNodeCount,defaultIdentityRiskNodeCount,duplicateVelocityServerNameNodeCount,routeCandidateEstimateNodeCount,routeCandidateRecommendedMinimum,routeCandidateShortfall,routeCandidateEstimatePolicy,elasticLimitPolicy,blockReason,physicalNodeNamesExposed\","
            + "\"islandPoolMultiNodeReady\":" + islandPoolMultiNodeReady(config, nodes) + ","
            + "\"islandPoolDegraded\":" + islandPoolDegraded(config, nodes) + ","
            + "\"islandPoolRouteCandidateShortfall\":" + islandPoolRouteCandidateShortfall(config, nodes) + ","
            + "\"islandPoolRouteCandidateBlockSummary\":\"" + escape(islandPoolRouteCandidateBlockSummary(config, nodes)) + "\","
            + "\"islandPoolBlockedNodeIds\":\"" + escape(islandPoolBlockedNodeIds(config, nodes)) + "\","
            + "\"islandPoolDuplicateVelocityServerNameNodeCount\":" + islandPoolDuplicateVelocityServerNameNodeCount(config, nodes) + ","
            + "\"islandPoolDefaultNodeIdentityRiskCount\":" + islandPoolDefaultNodeIdentityRiskCount(config, nodes) + ","
            + "\"softFullPolicy\":\"" + escape(config.softFullPolicy()) + "\","
            + "\"hardFullPolicy\":\"" + escape(config.hardFullPolicy()) + "\","
            + "\"softFullNewActivationAvoided\":" + avoidsSoftFullNewActivations(config.softFullPolicy()) + ","
            + "\"hardFullNewActivationAllowed\":" + allowsHardFullNewActivations(config.hardFullPolicy()) + ","
            + "\"nodeAllocatorNewActivationFallback\":\"READY nodes first, SOFT_FULL skipped by default so Island-2/next ready node receives new work when Island-1 is soft-full\","
            + "\"migrationPolicy\":\"" + escape(config.migrationPolicy()) + "\","
            + "\"superiorSkyblock2MigrationEnabled\":" + config.superiorSkyblock2MigrationEnabled() + ","
            + "\"superiorSkyblock2MigrationInputOnly\":true,"
            + "\"superiorSkyblock2RuntimeDependency\":false,"
            + "\"superiorSkyblock2RuntimePolicy\":\"migration-input-only-no-runtime-hooks\","
            + "\"superiorSkyblock2ReplacementFeatureCount\":" + kr.lunaf.cloudislands.common.feature.SuperiorSkyblockReplacementFeaturePolicy.requiredFeatureCount() + ","
            + "\"superiorSkyblock2ReplacementFeatures\":\"" + escape(kr.lunaf.cloudislands.common.feature.SuperiorSkyblockReplacementFeaturePolicy.requiredFeatureKeys()) + "\","
            + "\"superiorSkyblock2MigrationTargets\":\"" + escape(kr.lunaf.cloudislands.common.feature.SuperiorSkyblockReplacementFeaturePolicy.migrationTargetSummary()) + "\","
            + "\"superiorSkyblock2MigrationFlow\":\"" + escape(kr.lunaf.cloudislands.common.feature.SuperiorSkyblockReplacementFeaturePolicy.migrationStepSummary()) + "\","
            + "\"superiorSkyblock2MigrationCommands\":\"" + escape(kr.lunaf.cloudislands.common.feature.SuperiorSkyblockReplacementFeaturePolicy.migrationCommandSummary()) + "\","
            + "\"superiorSkyblock2MigrationEndpoints\":\"scan,status,dryrun,extract,import,verify,rollback\","
            + "\"superiorSkyblock2MigrationStatusEndpoint\":\"/v1/admin/migrations/superiorskyblock2/status\","
            + "\"superiorSkyblock2MigrationRollbackPolicy\":\"last-successful-import-only-consume-plan-after-success\","
            + "\"routeTicketTtlSeconds\":" + config.routeTicketTtl().toSeconds() + ","
            + "\"routePreparingTicketTtlSeconds\":" + config.routePreparingTicketTtl().toSeconds() + ","
            + "\"routeTicketOneTimeConsume\":" + kr.lunaf.cloudislands.protocol.route.RouteTicketPolicy.ONE_TIME_CONSUME + ","
            + "\"routeTicketNonceRequired\":" + kr.lunaf.cloudislands.protocol.route.RouteTicketPolicy.NONCE_REQUIRED + ","
            + "\"routeTicketTargetNodeRequired\":" + kr.lunaf.cloudislands.protocol.route.RouteTicketPolicy.TARGET_NODE_REQUIRED + ","
            + "\"routeTicketOneTimePolicy\":\"" + kr.lunaf.cloudislands.protocol.route.RouteTicketPolicy.ONE_TIME_POLICY + "\","
            + "\"routeTicketNoncePolicy\":\"" + kr.lunaf.cloudislands.protocol.route.RouteTicketPolicy.NONCE_POLICY + "\","
            + "\"routeTicketArrivalConsumePolicy\":\"" + kr.lunaf.cloudislands.protocol.route.RouteTicketPolicy.ARRIVAL_CONSUME_POLICY + "\","
            + "\"routeTicketDirectAccessPolicy\":\"" + kr.lunaf.cloudislands.protocol.route.RouteTicketPolicy.DIRECT_ACCESS_POLICY + "\","
            + "\"routeTicketReplayPolicy\":\"" + kr.lunaf.cloudislands.protocol.route.RouteTicketPolicy.REPLAY_POLICY + "\","
            + "\"routeTicketConsumeEndpoint\":\"/v1/routes/consume\","
            + "\"routeSessionConsumeEndpoint\":\"/v1/routes/session/consume\","
            + "\"routeSessionPreLoginGuard\":\"paper-async-prelogin-find-session-and-playerjoin-consume-session\","
            + "\"heartbeatTimeoutSeconds\":" + config.heartbeatTimeout().toSeconds() + ","
            + "\"leaseDurationSeconds\":" + config.leaseDuration().toSeconds() + ","
            + "\"cacheTierPolicy\":\"L1=paper-velocity-local-memory,L2=redis,L3=postgresql-mysql-mariadb-core-jdbc\","
            + "\"cacheAuthoritativeStorePolicy\":\"database-or-core-api-is-authority-redis-and-local-memory-are-discardable\","
            + "\"redisCacheTtlPolicy\":\"route-ticket=30s,player-island=300s,island-summary=60s,permissions=30s,locks=10-60s\","
            + "\"redisCacheTtlMillis\":\"serverHeartbeat=" + kr.lunaf.cloudislands.common.cache.RedisTtls.SERVER_HEARTBEAT_MILLIS
                + ",routeTicket=" + kr.lunaf.cloudislands.common.cache.RedisTtls.ROUTE_TICKET_MILLIS
                + ",playerIsland=" + kr.lunaf.cloudislands.common.cache.RedisTtls.PLAYER_ISLAND_MILLIS
                + ",playerProfile=" + kr.lunaf.cloudislands.common.cache.RedisTtls.PLAYER_PROFILE_MILLIS
                + ",islandSummary=" + kr.lunaf.cloudislands.common.cache.RedisTtls.ISLAND_SUMMARY_MILLIS
                + ",islandMetadata=" + kr.lunaf.cloudislands.common.cache.RedisTtls.ISLAND_METADATA_MILLIS
                + ",islandRuntime=" + kr.lunaf.cloudislands.common.cache.RedisTtls.ISLAND_RUNTIME_MILLIS
                + ",islandPermissions=" + kr.lunaf.cloudislands.common.cache.RedisTtls.ISLAND_PERMISSIONS_MILLIS
                + ",lockMin=" + kr.lunaf.cloudislands.common.cache.RedisTtls.LOCK_MIN_MILLIS
                + ",lockMax=" + kr.lunaf.cloudislands.common.cache.RedisTtls.LOCK_MAX_MILLIS + "\","
            + "\"redisKeyPolicy\":\"ci:server:{nodeId}:*,ci:player:{uuid}:*,ci:island:{islandId}:*,ci:lock:*,ci:stream:*\","
            + "\"cacheInvalidationSource\":\"core-write-transaction-then-global-event\","
            + "\"cacheInvalidationEvents\":\"IslandMemberChanged,IslandFlagChanged,IslandPermissionChanged,IslandWarpChanged,IslandRuntimeChanged,IslandDeleted\","
            + "\"cacheInvalidationEventFields\":\"cacheTargets,cacheKeys,cachePolicy\","
            + "\"cacheInvalidationFanout\":\"core-event-stream>paper-event-poller>velocity-route-cache-if-affected>local-cache-delete\","
            + "\"cacheInvalidationTargets\":\"player_uuid->island_id,island_id->summary,island_id->runtime,island_id->members,island_id->permissions,island_id->flags,island_id->warps,node_id->heartbeat\","
            + "\"cacheInvalidationRedisPatterns\":\"ci:player:*:island,ci:player:*:profile,ci:player-name:*:profile,ci:addon:*:state,ci:island:*:summary,ci:island:*:runtime,ci:island:*:members,ci:island:*:permissions,ci:island:*:flags,ci:island:*:warps,ci:island:*:addon-state,ci:island:*:route-tickets,ci:rankings:*\","
            + "\"addonStateGlobalCacheKey\":\"ci:addon:{addonId}:state\","
            + "\"addonStateIslandCacheKey\":\"ci:island:{islandId}:addon-state\","
            + "\"addonStateCacheInvalidationApi\":\"CacheInvalidationPlan.redisKeysFor(eventType,islandId,addonId)\","
            + "\"cacheRedisDownPolicy\":\"degraded-db-direct-read-no-data-loss-event-propagation-delayed-jobs-and-heartbeats-limited\","
            + "\"cacheCoreApiDownPolicy\":\"active-island-local-protection-continues-new-route-and-writes-limited\","
            + "\"redisStreamPolicy\":\"jobs,events,audit-append-only-observability\","
            + "\"globalEventTypes\":\"IslandCreated,IslandDeleted,IslandActivated,IslandDeactivated,IslandMigrated,IslandMemberChanged,IslandFlagChanged,IslandLevelUpdated,IslandSnapshotCreated,NodeStateChanged,RouteTicketCreated,RouteSessionPublished,RouteTicketConsumed,RouteTicketFailed,RouteTicketCleared\","
            + "\"globalEventTypeKeys\":\"" + escape(globalEventTypeKeys()) + "\","
            + "\"globalEventRecoveryKeys\":\"ISLAND_RUNTIME_CHANGED,ISLAND_RECOVERY_REQUIRED,ISLAND_REPAIRED,NODE_STATE_CHANGED\","
            + "\"globalEventAddonKeys\":\"ADDON_STATE_CHANGED\","
            + "\"routeMetricsTargetServerName\":true,"
            + "\"routeMetricsTargetServerNameEvents\":\"RouteTicketCreated,RouteSessionPublished,RouteTicketConsumed,RouteTicketFailed\","
            + "\"routeMetricsRequestedNode\":true,"
            + "\"routeMetricsRequestedNodeEvents\":\"RouteTicketFailed\","
            + "\"distributedLockPolicy\":\"redis-fast-lock-plus-postgresql-row-lock\","
            + "\"fencingTokenPolicy\":\"island_runtime.fencing_token-rejects-stale-node-writes\","
            + "\"jobCompletionContract\":\"" + kr.lunaf.cloudislands.protocol.job.IslandJobCompletionPolicy.CONTRACT + "\","
            + "\"jobCompletionFencingTokenKey\":\"" + kr.lunaf.cloudislands.protocol.job.IslandJobCompletionPolicy.FENCING_TOKEN_KEY + "\","
            + "\"jobCompletionStaleReasons\":\"" + kr.lunaf.cloudislands.protocol.job.IslandJobCompletionPolicy.STALE_FENCING_TOKEN + "," + kr.lunaf.cloudislands.protocol.job.IslandJobCompletionPolicy.STALE_NODE_COMPLETION + "," + kr.lunaf.cloudislands.protocol.job.IslandJobCompletionPolicy.RUNTIME_NOT_ACCEPTING_COMPLETION + "\","
            + "\"staleWritePolicy\":\"current-fencing-token-required-before-snapshot-or-runtime-write\","
            + "\"snapshotKeepLatest\":" + config.snapshotKeepLatest() + ","
            + "\"snapshotKeepHourly\":" + snapshotPolicy.keepHourly() + ","
            + "\"snapshotKeepDaily\":" + snapshotPolicy.keepDaily() + ","
            + "\"snapshotKeepWeekly\":" + snapshotPolicy.keepWeekly() + ","
            + "\"snapshotKeepManual\":" + snapshotPolicy.keepManual() + ","
            + "\"snapshotCompress\":" + snapshotPolicy.compress() + ","
            + "\"snapshotChecksumAlgorithm\":\"" + escape(snapshotPolicy.checksumAlgorithm()) + "\","
            + "\"snapshotRetentionMode\":\"hourly-daily-weekly-manual\","
            + "\"snapshotAutomaticTriggerPolicy\":\"" + escape(kr.lunaf.cloudislands.storage.snapshot.SnapshotOperationPolicy.AUTOMATIC_TRIGGER_POLICY) + "\","
            + "\"snapshotRequiredTriggerReasons\":\"" + escape(kr.lunaf.cloudislands.storage.snapshot.SnapshotOperationPolicy.automaticTriggerReasonSummary()) + "\","
            + "\"snapshotManualTriggerReason\":\"MANUAL\","
            + "\"snapshotPreRestoreReason\":\"BEFORE_RESTORE\","
            + "\"snapshotRestorePipeline\":\"" + escape(kr.lunaf.cloudislands.storage.snapshot.SnapshotOperationPolicy.RESTORE_PIPELINE_POLICY) + "\","
            + "\"snapshotRestoringLockState\":\"" + escape(kr.lunaf.cloudislands.storage.snapshot.SnapshotOperationPolicy.RESTORING_LOCK_STATE) + "\","
            + "\"snapshotRuntimeResetPolicy\":\"" + escape(kr.lunaf.cloudislands.storage.snapshot.SnapshotOperationPolicy.RUNTIME_RESET_POLICY) + "\","
            + "\"snapshotRollbackSteps\":\"" + escape(kr.lunaf.cloudislands.storage.snapshot.SnapshotOperationPolicy.rollbackStepSummary()) + "\","
            + "\"coreApiAuthPolicy\":\"token-or-mtls-required\","
            + "\"coreApiTokenConfigured\":" + (config.coreToken() != null && !config.coreToken().isBlank()) + ","
            + "\"coreApiMtlsRequired\":" + config.requireMtls() + ","
            + "\"coreApiAuthConfigured\":" + coreApiAuthConfigured(config) + ","
            + "\"coreApiAuthLockoutRisk\":" + !coreApiAuthConfigured(config) + ","
            + "\"adminPermissionPolicy\":\"separate-admin-permission-per-endpoint\","
            + "\"auditLogPolicy\":\"record-admin-player-and-system-actions\","
            + "\"controlChannelPolicy\":\"http-or-grpc-plus-redis-streams\","
            + "\"pluginMessagingPolicy\":\"not-used-for-critical-island-control\","
            + "\"requiredSecurityControls\":\"" + escape(String.join(",", kr.lunaf.cloudislands.common.security.BackendAccessPolicy.requiredSecurityControls())) + "\","
            + "\"velocityForwardingSecurityPolicy\":\"" + escape(kr.lunaf.cloudislands.common.security.BackendAccessPolicy.MODERN_FORWARDING_POLICY) + "\","
            + "\"paperDirectAccessSecurityPolicy\":\"" + escape(kr.lunaf.cloudislands.common.security.BackendAccessPolicy.PAPER_DIRECT_ACCESS_POLICY) + "\","
            + "\"coreApiSecurityPolicy\":\"" + escape(kr.lunaf.cloudislands.common.security.BackendAccessPolicy.CORE_API_AUTH_POLICY) + "\","
            + "\"infrastructureExposureSecurityPolicy\":\"" + escape(kr.lunaf.cloudislands.common.security.BackendAccessPolicy.INFRASTRUCTURE_EXPOSURE_POLICY) + "\","
            + "\"pluginMessagingSecurityPolicy\":\"" + escape(kr.lunaf.cloudislands.common.security.BackendAccessPolicy.PLUGIN_MESSAGING_POLICY) + "\","
            + "\"pluginMessagingAllowedUse\":\"emergency-proxy-assist-only\","
            + "\"pluginMessagingForbiddenUse\":\"island-create-delete-save-migrate-routing-authority\","
            + "\"paperAgentRolePolicy\":\"LOBBY handles menus-and-query-flow,ISLAND_NODE handles-world-runtime-protection-save-teleport\","
            + "\"paperLobbyRolePolicy\":\"no-island-world-execution-no-runtime-lease-no-shard-cell-ownership\","
            + "\"paperIslandNodeRolePolicy\":\"activate-save-snapshot-shard-cell-preload-protection-route-ticket-consume\","
            + "\"velocityCommandOwnershipPolicy\":\"/is-and-/섬-route-entry-owned-by-velocity-before-paper-fallback\","
            + "\"paperCommandFallbackPolicy\":\"paper-agent-keeps-local-gui-protection-and-bungee-connect-fallback-only\","
            + "\"createIslandFlowPolicy\":\"velocity-command-core-transaction-player-lock-node-allocator-create-job-agent-claim-template-restore-cell-runtime-active-route-ticket-ready-connect-teleport\","
            + "\"homeRouteFlowPolicy\":\"velocity-command-core-runtime-check-active-node-or-best-node-activation-route-ticket-ready-connect-paper-teleport\","
            + "\"visitRouteFlowPolicy\":\"target-island-lookup-public-ban-permission-check-active-or-activate-visitor-ticket-connect-visitor-spawn\","
            + "\"softFullRoutingPolicy\":\"new-and-inactive-islands-avoid-soft-full-nodes-active-members-may-use-reserved-slots-visitors-queue-or-deny\","
            + "\"newActivationSoftFullPolicy\":\"" + escape(config.softFullPolicy()) + "\","
            + "\"newActivationSoftFullAvoided\":" + avoidsSoftFullNewActivations(config.softFullPolicy()) + ","
            + "\"newActivationHardFullPolicy\":\"" + escape(config.hardFullPolicy()) + "\","
            + "\"newActivationHardFullAllowed\":" + allowsHardFullNewActivations(config.hardFullPolicy()) + ","
            + "\"portableIslandPolicy\":\"islands-are-global-portable-bundles-not-fixed-to-a-server-node\","
            + "\"portableIslandResourceModel\":\"" + kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.RESOURCE_MODEL + "\","
            + "\"portableIslandBundleModel\":\"" + kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.BUNDLE_MODEL + "\","
            + "\"portableIslandNodeModel\":\"" + kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.NODE_MODEL + "\","
            + "\"portableIslandPlayerVisibilityPolicy\":\"" + kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.PLAYER_VISIBILITY_POLICY + "\","
            + "\"portableIslandScalePolicy\":\"" + kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.SCALE_POLICY + "\","
            + "\"portableIslandFiveSixNodePolicy\":\"" + kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.FIVE_SIX_NODE_POLICY + "\","
            + "\"portableIslandScaleReadinessPolicy\":\"" + kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.SCALE_READINESS_POLICY + "\","
            + "\"portableIslandSoftFullPolicy\":\"" + kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.SOFT_FULL_POLICY + "\","
            + "\"portableIslandDesignEffects\":\"" + escape(kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.designEffectSummary()) + "\","
            + "\"portableIslandDefinition\":\"" + escape(kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.ONE_LINE_DEFINITION) + "\","
            + "\"nodeScaleOutPolicy\":\"add-island-nodes-with-unique-node-id-and-velocity-server-name-then-allocator-can-route-new-or-inactive-islands-there\","
            + "\"rankingUpdatePolicy\":\"" + escape(kr.lunaf.cloudislands.coreservice.ranking.RankingRecalculationService.UPDATE_POLICY) + "\","
            + "\"blockValuePolicy\":\"" + escape(kr.lunaf.cloudislands.coreservice.ranking.RankingRecalculationService.BLOCK_VALUE_POLICY) + "\","
            + "\"rankingFullScanPolicy\":\"" + escape(kr.lunaf.cloudislands.coreservice.ranking.RankingRecalculationService.FULL_SCAN_POLICY) + "\","
            + "\"rankingCachePolicy\":\"" + escape(kr.lunaf.cloudislands.coreservice.ranking.RankingRecalculationService.CACHE_POLICY) + "\","
            + "\"rankingDirtyBatchLimit\":" + kr.lunaf.cloudislands.coreservice.ranking.DirtyRankingRecalculationTask.BATCH_LIMIT + ","
            + "\"upgradePolicy\":\"" + escape(kr.lunaf.cloudislands.coreservice.upgrade.UpgradePolicy.CONFIG_DRIVEN_POLICY) + "\","
            + "\"upgradeTypePolicy\":\"" + escape(kr.lunaf.cloudislands.coreservice.upgrade.UpgradePolicy.SUPPORTED_TYPE_POLICY) + "\","
            + "\"upgradeEffectPolicy\":\"" + escape(kr.lunaf.cloudislands.coreservice.upgrade.UpgradePolicy.EFFECT_APPLICATION_POLICY) + "\","
            + "\"upgradePurchasePolicy\":\"" + escape(kr.lunaf.cloudislands.coreservice.upgrade.IslandUpgradeService.PURCHASE_POLICY) + "\","
            + "\"upgradeEconomyPolicy\":\"" + escape(kr.lunaf.cloudislands.coreservice.upgrade.IslandUpgradeService.ECONOMY_ABSTRACTION_POLICY) + "\","
            + "\"paperUpgradeEconomyPolicy\":\"paper-agent-uses-economy-bridge-for-player-facing-upgrade-purchase\","
            + "\"generatorPolicy\":\"paper-agent-local-generator-rules-by-island-upgrade-level\","
            + "\"superiorSkyblock2ReplacementPolicy\":\"built-in-cloudislands-modules-replace-superiorskyblock2-runtime-dependency\","
            + "\"superiorSkyblock2ReplacementFeatures\":\"create,template-select,delete,reset,home,multiple-homes,visit,random-visit,public-private,visitor-ban,visitor-kick,member-invite,member-kick,roles-permissions,custom-roles,flags,warps,ranking,level,worth,block-values,upgrades,size-expansion,border,biome,bank,island-chat,team-chat,missions,challenges,generator-upgrades,spawner-limits,hopper-limits,entity-limits,redstone-limits,island-logs,admin-recovery,snapshots-rollback,migration,server-drain,distributed-api,web-api,external-java-api\","
            + "\"superiorSkyblock2ReplacementFeatureGate\":\"core-config-and-addon-feature-flags-can-disable-optional-satis-compatible-features\","
            + "\"infrastructureExposurePolicy\":\"redis-postgresql-object-storage-private-only\","
            + "\"publicBindRiskPolicy\":\"require-ip-allowlist-or-private-bind\","
            + "\"adminApiEnabled\":" + config.adminApiEnabled() + ","
            + "\"requireMtls\":" + config.requireMtls() + ","
            + "\"ipAllowlistEnabled\":" + (config.ipAllowlist() != null && !config.ipAllowlist().isBlank()) + ","
            + "\"requiredSecurityControls\":\"" + escape(String.join(",", kr.lunaf.cloudislands.common.security.BackendAccessPolicy.requiredSecurityControls())) + "\","
            + "\"pluginMessagingSecurityPolicy\":\"" + escape(kr.lunaf.cloudislands.common.security.BackendAccessPolicy.PLUGIN_MESSAGING_POLICY) + "\","
            + "\"rateLimitRequests\":" + config.rateLimitRequests() + ","
            + "\"rateLimitWindowSeconds\":" + config.rateLimitWindow().toSeconds()
            + "}";
    }


    private static String escape(String value) {
        return value == null ? "" : value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private static boolean avoidsSoftFullNewActivations(String policy) {
        return policy == null
            || policy.isBlank()
            || policy.equalsIgnoreCase("AVOID_NEW_ACTIVATIONS")
            || policy.equalsIgnoreCase("READY_ONLY");
    }

    private static boolean allowsHardFullNewActivations(String policy) {
        return policy != null
            && (policy.equalsIgnoreCase("ALLOW_NEW_ACTIVATIONS")
                || policy.equalsIgnoreCase("ALLOW")
                || policy.equalsIgnoreCase("IGNORE_HARD_FULL"));
    }
}
