package kr.lunaf.cloudislands.coreservice.http.routes;

import static kr.lunaf.cloudislands.coreservice.config.CoreIslandPoolSummary.*;
import static kr.lunaf.cloudislands.coreservice.config.CoreNetworkExposure.*;
import static kr.lunaf.cloudislands.coreservice.config.CoreSetupSummary.*;

import java.io.IOException;
import java.util.LinkedHashMap;
import kr.lunaf.cloudislands.api.model.AddonStateBulkLoadRequest;
import kr.lunaf.cloudislands.api.model.AddonStateBulkSaveRequest;
import kr.lunaf.cloudislands.common.json.SimpleJson;
import kr.lunaf.cloudislands.coreservice.IslandPlacement;
import kr.lunaf.cloudislands.coreservice.NodeRegistry;
import kr.lunaf.cloudislands.coreservice.addon.AddonStateRepository;
import kr.lunaf.cloudislands.coreservice.config.CoreServiceConfig;
import kr.lunaf.cloudislands.coreservice.http.CoreHttpResponses;
import kr.lunaf.cloudislands.coreservice.http.CoreRouteRegistry;
import kr.lunaf.cloudislands.coreservice.http.RouteGroup;
import kr.lunaf.cloudislands.protocol.node.NodeHeartbeatRequest;

public final class CoreConfigRoutes implements RouteGroup {
    private static final int MIN_NODE_PROTOCOL_VERSION = 1;
    private static final int MAX_NODE_PROTOCOL_VERSION = NodeHeartbeatRequest.CURRENT_PROTOCOL_VERSION;

    private final CoreServiceConfig config;
    private final NodeRegistry nodes;

    public CoreConfigRoutes(CoreServiceConfig config, NodeRegistry nodes) {
        this.config = config;
        this.nodes = nodes;
    }

    @Override
    public void register(CoreRouteRegistry registry) {
        registry.route("/v1/admin/config", this::config);
    }

    private void config(com.sun.net.httpserver.HttpExchange exchange) throws IOException {
        CoreHttpResponses.write(exchange, 200, configSummaryJson());
    }

    private static String storageBackendSafety(CoreServiceConfig config) {
        if (config == null || config.storageType() == null || config.storageType().isBlank()) {
            return "unknown-storage-backend";
        }
        if ("S3".equalsIgnoreCase(config.storageType())) {
            return "shared-object-storage-safe-for-multi-node-island-pools";
        }
        if ("LOCAL".equalsIgnoreCase(config.storageType())) {
            return "local-storage-requires-shared-filesystem-mount-for-multi-node-island-pools";
        }
        return "unsupported-storage-backend";
    }

    String configSummaryJson() {
        kr.lunaf.cloudislands.storage.snapshot.SnapshotRetentionPolicy snapshotPolicy = config.snapshotRetentionPolicy().normalized();
        LinkedHashMap<String, Object> summary = new LinkedHashMap<>();
        summary.put("repositoryMode", config.repositoryMode());
        summary.put("jobQueueMode", config.jobQueueMode());
        summary.put("eventBusMode", config.eventBusMode());
        summary.put("effectiveRepositoryMode", (config.jdbcRepositories() ? "JDBC" : "IN_MEMORY"));
        summary.put("effectiveJobQueueMode", (config.jdbcJobs() ? "JDBC" : config.redisJobs() ? "REDIS" : "IN_MEMORY"));
        summary.put("effectiveEventBusMode", (config.redisEvents() ? "REDIS" : "IN_MEMORY"));
        summary.put("coreJdbcRepositoriesEnabled", config.jdbcRepositories());
        summary.put("coreJdbcJobsEnabled", config.jdbcJobs());
        summary.put("configuredDatabaseType", config.configuredDatabaseType());
        summary.put("configuredDatabaseTypeSource", CoreServiceConfig.configuredDatabaseTypeSource());
        summary.put("runtimeMode", config.runtimeMode());
        summary.put("databaseBackend", jdbcBackend(config.jdbcUrl()));
        summary.put("jdbcUrlSource", CoreServiceConfig.configuredJdbcUrlSource());
        summary.put("effectiveJdbcSettingsType", CoreServiceConfig.configuredJdbcSettingsType());
        summary.put("effectiveJdbcSettingsSource", CoreServiceConfig.configuredJdbcSettingsSource());
        summary.put("coreJdbcSupported", coreJdbcSupported(config.jdbcUrl()));
        summary.put("coreJdbcSupportedBackends", "POSTGRESQL,MYSQL,MARIADB");
        summary.put("coreSetupFallbackBackends", "POSTGRESQL,MYSQL,MARIADB,CORE_API,UNSUPPORTED_JDBC");
        summary.put("coreSetupFallbackRequireSharedBeforeLocal", config.setupDatabaseFallbackRequireSharedBeforeLocal());
        summary.put("coreSetupFallbackLocalLast", config.setupDatabaseFallbackLocalLast());
        summary.put("coreSetupFallbackProductionSafeOrder", config.setupDatabaseFallbackProductionSafeOrder());
        summary.put("coreSetupDatabaseAutoSchema", config.setupDatabaseAutoSchema());
        summary.put("coreSetupDatabaseAutoSchemaPolicy", "explicit-opt-in-postgresql-mysql-mariadb-bootstrap");
        summary.put("coreSetupDatabaseAutoSchemaResource", "postgresql=/db/migration/V1..V66,mysql-mariadb=/db/mysql/V1__cloudislands_mysql_schema.sql");
        summary.put("coreSetupDatabaseAutoSchemaHistoryTable", "cloudislands_schema_bootstrap");
        summary.put("coreSetupDatabaseAutoSchemaRetryPolicy", "ignore-existing-schema-objects-and-mark-bootstrap-after-complete-apply");
        summary.put("coreSetupDatabaseAutoSchemaGuardPolicy", "generated-columns-enforce-active-unique-guards-for-mysql-mariadb");
        summary.put("coreSetupFallbackEnabled", config.setupDatabaseFallbackEnabled());
        summary.put("coreSetupAllowInMemoryFallback", config.setupDatabaseAllowInMemoryFallback());
        summary.put("coreSetupFallbackEffective", coreJdbcFallbackActive(config));
        summary.put("coreSetupFallbackSafetyForced", coreSetupFallbackSafetyForced(config));
        summary.put("coreSetupFallbackPolicy", coreSetupFallbackPolicy(config));
        summary.put("coreSetupFallbackOrder", config.setupDatabaseFallbackOrder());
        summary.put("coreSetupFallbackMode", coreSetupFallbackMode(config));
        summary.put("coreSetupDatabaseRequestedBackend", config.setupDatabaseRequestedBackend());
        summary.put("coreSetupDatabaseEffectiveAuthority", config.setupDatabaseEffectiveAuthority());
        summary.put("coreSetupDatabaseEffectiveBackend", config.setupDatabaseEffectiveBackend());
        summary.put("coreSetupDatabaseFallbackTarget", config.setupDatabaseFallbackTarget());
        summary.put("coreSetupDatabasePostgresqlFallbackConfigured", config.setupDatabasePostgresqlFallbackConfigured());
        summary.put("coreSetupDatabaseMysqlFallbackConfigured", config.setupDatabaseMysqlFallbackConfigured());
        summary.put("coreSetupDatabaseMariadbFallbackConfigured", config.setupDatabaseMariadbFallbackConfigured());
        summary.put("coreSetupDatabaseCoreApiFallbackConfigured", config.setupDatabaseCoreApiFallbackConfigured());
        summary.put("coreSetupDatabaseFallbackReason", config.setupDatabaseFallbackReason());
        summary.put("coreSetupDatabaseFallbackSummary", config.setupDatabaseFallbackSummary());
        summary.put("coreSetupDatabaseFallbackCandidateChain", coreSetupFallbackCandidateChain(config));
        summary.put("coreSetupDatabaseFallbackReadyBackends", coreSetupFallbackReadyBackends(config));
        summary.put("coreSetupDatabaseFallbackMissingBackends", coreSetupFallbackMissingBackends(config));
        summary.put("coreSetupDatabaseFallbackDecision", coreSetupFallbackDecision(config));
        summary.put("coreSetupDatabaseDurable", config.setupDatabaseDurable());
        summary.put("coreSetupDatabaseProductionDurable", config.setupDatabaseProductionDurable());
        summary.put("coreSetupDatabaseReady", config.setupDatabaseReady());
        summary.put("coreSetupDatabaseFallbackSafetyForced", config.setupDatabaseFallbackSafetyForced());
        summary.put("coreSetupDatabaseFallbackSafetyMode", config.setupDatabaseFallbackSafetyMode());
        summary.put("coreSetupDatabaseOperationalModes", "POSTGRESQL=CORE_JDBC,MYSQL=CORE_JDBC,MARIADB=CORE_JDBC,CORE_API=CLIENT_MODE_NO_CORE_SERVICE_SELF_STORAGE");
        summary.put("coreSetupDatabasePrimaryAuthority", "POSTGRESQL_MYSQL_MARIADB_FOR_CORE_STATE_CORE_API_FOR_CLIENT_ADDON_STATE");
        summary.put("coreSetupDatabaseMysqlPolicy", "native-core-jdbc-through-setup.database.mysql-or-jdbc-url");
        summary.put("coreSetupDatabaseMariadbPolicy", "native-core-jdbc-through-setup.database.mariadb-or-jdbc-url");
        summary.put("coreSetupDatabaseCoreApiPolicy", "client-addon-state-marker-core-self-storage-requires-durable-jdbc-or-explicit-non-production-in-memory-fallback");
        summary.put("coreSetupDatabaseSafeFallbackWarning", "IN_MEMORY_CORE_FALLBACK_IS_NON_DURABLE_AND_NOT_READY_FOR_PRODUCTION");
        summary.put("coreSetupDatabaseConfigLoader", "yaml-nested-dotted-path");
        summary.put("coreSetupDatabaseResolvedPathExamples", "setup.database.type,setup.database.postgresql.jdbc-url,setup.database.postgresql.username,setup.database.mysql.host,setup.database.mysql.password,setup.database.mariadb.pool-size,setup.database.core-api.enabled");
        summary.put("coreSetupDatabaseConfigShapes", "setup.database.*,setup.database-*,setup.database.fallback.order(list-or-comma-string)");
        summary.put("coreSetupDatabaseTypedShapes", "setup.database.postgresql.*,setup.database.mysql.*,setup.database.mariadb.*,setup.database.core-api.*");
        summary.put("coreSetupDatabaseTypedCredentialKeys", "username,password,pool-size");
        summary.put("coreSetupDatabaseTypedHostMode", "requires-type-or-typed-url-inference");
        summary.put("coreSetupDatabaseTypedProbeOrder", "postgresql,mysql,mariadb");
        summary.put("coreSetupDatabaseCoreApiMode", "enabled-marker-no-core-jdbc");
        summary.put("coreSetupDatabaseCoreApiBaseUrl", config.setupDatabaseCoreApiBaseUrl());
        summary.put("coreSetupDatabaseCoreApiAuthTokenConfigured", config.setupDatabaseCoreApiAuthTokenConfigured());
        summary.put("coreSetupDatabaseCoreApiAdminTokenConfigured", config.setupDatabaseCoreApiAdminTokenConfigured());
        summary.put("coreSetupDatabaseCoreApiTimeoutMs", config.setupDatabaseCoreApiTimeoutMillis());
        summary.put("coreSetupDatabaseCoreApiClientMode", config.setupDatabaseCoreApiClientMode());
        summary.put("coreSetupDatabaseCoreApiClientReady", config.setupDatabaseCoreApiClientReady());
        summary.put("coreSetupDatabaseFallbackReadiness", config.setupDatabaseFallbackReadiness());
        summary.put("coreSetupDatabaseCoreApiConfigPaths", "setup.database.core-api.base-url,setup.database.core-api.url,setup.database.core-api.auth-token,setup.database.core-api.admin-token,setup.database.core-api.timeout-ms,setup.core-api.*,setup-core-api.*,core-api.*");
        summary.put("coreSetupDatabaseEnv", "CI_DATABASE_TYPE,CI_JDBC_URL,CI_DB_USERNAME,CI_DB_PASSWORD,CI_DB_POOL_SIZE,CI_DB_AUTO_SCHEMA,CI_DB_FALLBACK_ENABLED,CI_DB_FALLBACK_ORDER,CI_SETUP_CORE_API_BASE_URL,CI_SETUP_CORE_API_AUTH_TOKEN,CI_SETUP_CORE_API_ADMIN_TOKEN,CI_SETUP_CORE_API_TIMEOUT_MS");
        summary.put("coreSetupDatabasePrecedence", "env,nested-setup-database,legacy-flat-setup,database-default");
        summary.put("coreSetupDatabaseNameAliases", "setup.database.name,setup.database.database,setup.database-name");
        summary.put("nodeAllocatorPolicy", "pool-filter-unique-velocity-server-fresh-heartbeat-storage-ready-template-version-capacity-then-weighted-score");
        summary.put("nodeAllocatorScoreWeights", "players=0.25,activeIslands=0.15,mspt=0.25,activationQueue=0.15,chunkLoad=0.10,memory=0.05,recentFailure=0.05");
        summary.put("nodeAllocatorHardRules", "READY-or-policy-allowed-SOFT_FULL,heartbeat-fresh,storage-available,hard-player-cap,max-active-islands,max-activation-queue,template-supported,min-node-version,unique-velocity-server-name,non-default-node-identity");
        summary.put("nodeAllocatorFiveSixNodePolicy", "no-fixed-node-count-limit-add-island-nodes-with-unique-node-id-unique-velocity-server-name-shared-storage");
        summary.put("coreSetupDatabaseJdbcAliases", "CI_JDBC_URL,setup.database.jdbc-url,setup.jdbc-url,database.jdbc-url");
        summary.put("coreSetupDatabaseTypeInference", "CI_DATABASE_TYPE,setup.database.type,setup.database-type,setup.database.core-api.enabled,CI_JDBC_URL,setup.database.jdbc-url,setup.jdbc-url,setup.database.postgresql.jdbc-url,setup.database.postgresql.url,setup.database.mysql.jdbc-url,setup.database.mysql.url,setup.database.mariadb.jdbc-url,setup.database.mariadb.url,typed-host-name,database.jdbc-url");
        summary.put("observabilityMetricsPolicy", "prometheus-exporter-covers-node-island-route-permission-job-storage-database-redis-metrics");
        summary.put("observabilityRequiredMetrics", "cloudislands_nodes_online,cloudislands_node_players,cloudislands_node_mspt,cloudislands_node_active_islands,cloudislands_node_activation_queue,cloudislands_island_activation_seconds,cloudislands_island_save_seconds,cloudislands_island_snapshot_seconds,cloudislands_route_ticket_created_total,cloudislands_route_ticket_failed_total,cloudislands_permission_checks_total,cloudislands_permission_cache_hit_ratio,cloudislands_jobs_pending,cloudislands_jobs_failed_total,cloudislands_jobs_retry_total,cloudislands_storage_upload_seconds,cloudislands_storage_download_seconds,cloudislands_database_query_seconds,cloudislands_redis_latency_seconds");
        summary.put("observabilityRequiredDashboardPanels", "nodes-online,node-players,node-mspt,active-islands,activation-seconds,island-save-failures,route-failures,redis-latency,database-pool-usage,object-storage-failure-ratio");
        summary.put("observabilityDashboardPolicy", "grafana-dashboard-must-show-node-load-activation-save-route-redis-db-and-object-storage-health");
        summary.put("coreJdbcFallbackReason", coreJdbcFallbackReason(config));
        summary.put("coreJdbcFallbackActive", coreJdbcFallbackActive(config));
        summary.put("coreJdbcFallbackStatus", coreJdbcFallbackStatus(config));
        summary.put("addonStateBulkSaveApi", true);
        summary.put("addonStateBulkSaveGlobalEndpoint", AddonStateBulkSaveRequest.GLOBAL_LEGACY_ENDPOINT);
        summary.put("addonStateBulkSaveIslandEndpoint", AddonStateBulkSaveRequest.ISLAND_LEGACY_ENDPOINT);
        summary.put("addonStateTableKeyValueBulkSaveGlobalEndpoint", AddonStateBulkSaveRequest.GLOBAL_ENDPOINT);
        summary.put("addonStateTableKeyValueBulkSaveIslandEndpoint", AddonStateBulkSaveRequest.ISLAND_ENDPOINT);
        summary.put("addonStateTableKeyValueBulkSaveGlobalAlias", AddonStateBulkSaveRequest.GLOBAL_BULK_SAVE_ALIAS);
        summary.put("addonStateTableKeyValueBulkSaveIslandAlias", AddonStateBulkSaveRequest.ISLAND_BULK_SAVE_ALIAS);
        summary.put("addonStateTableKeyValueBulkGlobalEndpoint", AddonStateBulkSaveRequest.GLOBAL_BULK_ALIAS);
        summary.put("addonStateTableKeyValueBulkIslandEndpoint", AddonStateBulkSaveRequest.ISLAND_BULK_ALIAS);
        summary.put("addonStateTableKeyValueBulkSaveGlobalAliases", String.join(",", AddonStateBulkSaveRequest.GLOBAL_ENDPOINTS));
        summary.put("addonStateTableKeyValueBulkSaveIslandAliases", String.join(",", AddonStateBulkSaveRequest.ISLAND_ENDPOINTS));
        summary.put("addonStateTableKeyValueBulkLoadGlobalEndpoint", AddonStateBulkLoadRequest.GLOBAL_ENDPOINT);
        summary.put("addonStateTableKeyValueBulkLoadIslandEndpoint", AddonStateBulkLoadRequest.ISLAND_ENDPOINT);
        summary.put("addonStateTableKeyValueBulkLoadGlobalAliases", String.join(",", AddonStateBulkLoadRequest.GLOBAL_ENDPOINTS));
        summary.put("addonStateTableKeyValueBulkLoadIslandAliases", String.join(",", AddonStateBulkLoadRequest.ISLAND_ENDPOINTS));
        summary.put("addonStateTableLoadGlobalEndpoint", AddonStateBulkLoadRequest.GLOBAL_TABLE_LOAD_ALIAS);
        summary.put("addonStateTableLoadIslandEndpoint", AddonStateBulkLoadRequest.ISLAND_TABLE_LOAD_ALIAS);
        summary.put("addonStateTableBulkGlobalEndpoint", AddonStateBulkSaveRequest.GLOBAL_TABLE_BULK_ENDPOINT);
        summary.put("addonStateTableBulkIslandEndpoint", AddonStateBulkSaveRequest.ISLAND_TABLE_BULK_ENDPOINT);
        summary.put("addonStateTableBulkSetGlobalEndpoint", AddonStateBulkSaveRequest.GLOBAL_TABLE_BULK_SET_ENDPOINT);
        summary.put("addonStateTableBulkSetIslandEndpoint", AddonStateBulkSaveRequest.ISLAND_TABLE_BULK_SET_ENDPOINT);
        summary.put("addonStateTableKeyValueBulkSavePayload", "addonId,islandId(optional),values,tables");
        summary.put("addonStateTableKeyValueBulkLoadPayload", "addonId,islandId(optional),table");
        summary.put("addonStateTableKeyValueBulkSaveStorageMode", "table-prefix-flattened-key-value");
        summary.put("addonStateTableKeyValueBulkSaveRepositoryApi", "AddonStateRepository.tableKeyValueBulkSave,AddonStateRepository.tableKeyValueBulkSaveIsland,AddonStateRepository.tableBulk,AddonStateRepository.tableBulkIsland,AddonStateRepository.tableKeyValueBulkLoad,AddonStateRepository.tableKeyValueBulkLoadIsland,AddonStateBulkSaveRequest,AddonStateBulkLoadRequest,IslandAddonService.tableBulkState,IslandAddonService.tableBulkIslandState,IslandAddonService.tableKeyValueBulkSaveState,IslandAddonService.tableKeyValueBulkSaveIslandState,IslandAddonService.tableKeyValueBulkLoadState,IslandAddonService.tableKeyValueBulkLoadIslandState,IslandAddonService.tableLoadState,IslandAddonService.tableLoadIslandState,CoreApiClient.tableKeyValueBulkSaveAddonState,CoreApiClient.tableKeyValueBulkSaveAddonIslandState,CoreApiClient.tableBulkAddonState,CoreApiClient.tableBulkAddonIslandState,CoreApiClient.tableKeyValueBulkLoadAddonState,CoreApiClient.tableKeyValueBulkLoadAddonIslandState,CoreApiClient.tableLoadAddonState,CoreApiClient.tableLoadAddonIslandState");
        summary.put("addonStateTableKeyPrefix", AddonStateRepository.TABLE_STATE_KEY_SHAPE);
        summary.put("addonStateMaxAddonIdLength", AddonStateRepository.MAX_ADDON_ID_LENGTH);
        summary.put("addonStateMaxKeyLength", AddonStateRepository.MAX_KEY_LENGTH);
        summary.put("addonStateMaxValueLength", AddonStateRepository.MAX_VALUE_LENGTH);
        summary.put("addonStateMaxKeysPerAddon", AddonStateRepository.MAX_KEYS_PER_ADDON);
        summary.put("addonStateTableKeyValueBulkSaveFallback", "local-cache-on-core-api-failure");
        summary.put("addonStateTableKeyValueBulkLoadFallback", "local-cache-or-empty-table-on-core-api-failure");
        summary.put("databasePoolSize", config.databasePoolSize());
        summary.put("storageType", config.storageType());
        summary.put("storageSharedBackend", ("S3".equalsIgnoreCase(config.storageType())));
        summary.put("storageMultiNodeSafe", ("S3".equalsIgnoreCase(config.storageType())));
        summary.put("storageBackendSafety", storageBackendSafety(config));
        summary.put("storageLocalMultiNodePolicy", "LOCAL requires the same shared filesystem mount on every Island node; otherwise use S3 or MinIO");
        summary.put("storageS3MultiNodePolicy", "S3 or MinIO is the recommended shared object storage for 5/6 Island node pools");
        summary.put("storageLayout", "islands/{islandUuid}/manifest.json,latest,snapshots/{snapshotNo}/bundle.tar.zst,checksums.sha256,backups,recovery");
        summary.put("storageLatestPointer", "islands/{islandUuid}/latest");
        summary.put("storageSnapshotManifest", "islands/{islandUuid}/snapshots/{snapshotNo}/manifest.json");
        summary.put("storageBundleObject", "islands/{islandUuid}/snapshots/{snapshotNo}/bundle.tar.zst");
        summary.put("storageChecksumFile", "islands/{islandUuid}/snapshots/{snapshotNo}/checksums.sha256");
        summary.put("storageDeleteBackupPath", "islands/{islandUuid}/backups/delete-{snapshotNo}");
        summary.put("storageRecoveryPath", "islands/{islandUuid}/recovery");
        summary.put("storagePortabilityPolicy", "bundle-and-manifest-are-island-uuid-scoped-node-independent");
        summary.put("storageRestoreManifestRequired", true);
        summary.put("storageRestoreChecksumPolicy", "verify-manifest-checksum-for-latest-snapshot-and-storage-path");
        summary.put("storageRestorePortableRequired", true);
        summary.put("storageRestoreSupportedFormats", "checksum=SHA-256,compression=zstd");
        summary.put("failureHandlingNodeDownPolicy", "heartbeat-timeout>node-down>block-new-routes>mark-active-islands-recovery-required>fallback-players-lobby>snapshot-check>recover-on-other-node-or-quarantine");
        summary.put("failureHandlingRecoveryRequiredPolicy", kr.lunaf.cloudislands.common.runtime.IslandRuntimeStatePolicy.RECOVERY_REQUIRED_POLICY);
        summary.put("failureHandlingCoreApiDownAllowed", "active-island-play,local-cache-protection,basic-local-teleport-fallback");
        summary.put("failureHandlingCoreApiDownLimited", "new-island-create,inactive-island-activation,island-route,member-change,flag-change");
        summary.put("failureHandlingCoreApiDownPlayerMessage", "현재 섬 서비스 일부 기능이 점검 중입니다.");
        summary.put("failureHandlingRedisDownAllowed", "database-direct-read-degraded-mode-without-data-loss");
        summary.put("failureHandlingRedisDownLimited", "cache-performance,event-propagation,job-queue-processing,heartbeat-freshness");
        summary.put("failureHandlingRedisDownRecommendation", "run-redis-high-availability-in-production");
        summary.put("failureHandlingObjectStorageDownAllowed", "already-active-island-play-continues-on-node-local-world");
        summary.put("failureHandlingObjectStorageDownLimited", "new-activation,island-save,snapshot,recovery");
        summary.put("failureHandlingObjectStorageRetryPolicy", "queue-failed-save-and-snapshot-operations-for-retry-while-primary-storage-is-unavailable");
        summary.put("failureHandlingQuarantinePolicy", kr.lunaf.cloudislands.common.runtime.IslandRuntimeStatePolicy.QUARANTINE_POLICY);
        summary.put("failureHandlingRecoveryStateSummary", kr.lunaf.cloudislands.common.runtime.IslandRuntimeStatePolicy.recoveryStateSummary());
        summary.put("islandResourceModel", "global-resource");
        summary.put("islandPortableBundle", true);
        summary.put("islandServerPinned", false);
        summary.put("islandExecutionModel", "dynamic-island-node-pool");
        summary.put("islandNodeRole", "runtime-execution-node-only");
        summary.put("islandRoutingModel", "route-ticket-to-active-or-best-node");
        summary.put("createIslandRequestFlow", "velocity-command>core-createIsland>db-transaction-lock>node-allocator>create-island-job>agent-claim>template-restore>cell-allocate>runtime-active>route-ticket-ready>velocity-connect>paper-consume-ticket>spawn-teleport");
        summary.put("createIslandDuplicateGuard", "redis-player-creation-lock-plus-jdbc-player-profile-for-update");
        summary.put("createIslandJdbcLockPolicy", "upsert-player-profile-select-for-update-then-owner-island-select-for-update");
        summary.put("createIslandTransactionScope", "islands-row-owner-member-runtime-primary-island");
        summary.put("createIslandJobPolicy", "commit-before-job-publish-error-state-on-job-queue-failure");
        summary.put("createIslandInitialTicketState", "PREPARING-until-paper-agent-completes-create-job");
        summary.put("homeRequestFlow", "velocity-command>core-createHomeRoute>runtime-check>active-or-activate-best-node>route-ticket-ready>velocity-connect>paper-teleport");
        summary.put("visitRequestFlow", "velocity-command>target-island-lookup>public-ban-permission-check>active-or-activate>visitor-ticket>velocity-connect>visitor-spawn-teleport");
        summary.put("routePlayerLoadingUi", "actionbar-and-bossbar-progress-without-node-name");
        summary.put("routePlayerFailureCodes", kr.lunaf.cloudislands.common.routing.RouteFailurePolicy.PUBLIC_FAILURE_CODES);
        summary.put("routePlayerFailureMessages", kr.lunaf.cloudislands.common.routing.RouteFailurePolicy.publicMessageSummary());
        summary.put("routePublicMessagePolicy", kr.lunaf.cloudislands.common.routing.RouteFailurePolicy.PUBLIC_MESSAGE_POLICY);
        summary.put("routeDebugReasonPolicy", kr.lunaf.cloudislands.common.routing.RouteFailurePolicy.DEBUG_REASON_POLICY);
        summary.put("routeVisitRejectionPolicy", kr.lunaf.cloudislands.common.routing.RouteFailurePolicy.VISIT_REJECTION_POLICY);
        summary.put("routeTransferFailurePolicy", "clear-ticket-session-and-show-public-message-or-return-lobby");
        summary.put("softFullRoutingPolicy", "new-and-inactive-islands-use-ready-node-active-owner-member-reserve-current-node-visitors-queue-or-limit");
        summary.put("newActivationSoftFullPolicy", config.softFullPolicy());
        summary.put("newActivationSoftFullAvoided", avoidsSoftFullNewActivations(config.softFullPolicy()));
        summary.put("newActivationHardFullPolicy", config.hardFullPolicy());
        summary.put("newActivationHardFullAllowed", allowsHardFullNewActivations(config.hardFullPolicy()));
        summary.put("softFullNewActivationBehavior", "ready-node-preferred-soft-full-avoided-unless-policy-allows");
        summary.put("softFullExistingRouteBehavior", "active-owner-member-routes-can-use-current-soft-full-node-visitors-queue-or-limit");
        summary.put("moduleLayout", kr.lunaf.cloudislands.common.packaging.CloudIslandsModuleLayoutPolicy.requiredModuleSummary());
        summary.put("coreModuleLayout", kr.lunaf.cloudislands.common.packaging.CloudIslandsModuleLayoutPolicy.requiredModuleSummary());
        summary.put("addonModuleLayout", kr.lunaf.cloudislands.common.packaging.CloudIslandsModuleLayoutPolicy.optionalExtensionModuleSummary());
        summary.put("moduleResponsibilityLayout", kr.lunaf.cloudislands.common.packaging.CloudIslandsModuleLayoutPolicy.moduleResponsibilitySummary());
        summary.put("moduleRuntimeSurfaceLayout", kr.lunaf.cloudislands.common.packaging.CloudIslandsModuleLayoutPolicy.moduleRuntimeSurfaceSummary());
        summary.put("distributionLayout", kr.lunaf.cloudislands.common.packaging.CloudIslandsModuleLayoutPolicy.distributionArtifactSummary());
        summary.put("distributionTaskLayout", kr.lunaf.cloudislands.common.packaging.CloudIslandsModuleLayoutPolicy.distributionTaskSummary());
        summary.put("distributionMarkdownPackagingGuard", "verifyMarkdownDocsExcludedFromArtifacts-before-build-and-distBundle");
        summary.put("productionReadinessContract", kr.lunaf.cloudislands.common.observability.ProductionReadinessPolicy.CONTRACT);
        summary.put("productionReadinessGates", kr.lunaf.cloudislands.common.observability.ProductionReadinessPolicy.requiredGateSummary());
        summary.put("productionDeploymentTemplatePolicy", kr.lunaf.cloudislands.common.observability.ProductionReadinessPolicy.DEPLOYMENT_TEMPLATE_POLICY);
        summary.put("productionRollingUpgradePolicy", kr.lunaf.cloudislands.common.observability.ProductionReadinessPolicy.ROLLING_UPGRADE_POLICY);
        summary.put("productionE2ePolicy", kr.lunaf.cloudislands.common.observability.ProductionReadinessPolicy.E2E_POLICY);
        summary.put("productionChaosPolicy", kr.lunaf.cloudislands.common.observability.ProductionReadinessPolicy.CHAOS_POLICY);
        summary.put("productionBackupRestorePolicy", kr.lunaf.cloudislands.common.observability.ProductionReadinessPolicy.BACKUP_RESTORE_POLICY);
        summary.put("productionSupportBundlePolicy", kr.lunaf.cloudislands.common.observability.ProductionReadinessPolicy.SUPPORT_BUNDLE_POLICY);
        summary.put("productionGaDrillContract", kr.lunaf.cloudislands.common.observability.ProductionGaDrillMatrix.CONTRACT);
        summary.put("productionGaDrillEvidence", kr.lunaf.cloudislands.common.observability.ProductionGaDrillMatrix.evidenceSummary());
        summary.put("productionGaFailureInjectionScenarios", kr.lunaf.cloudislands.common.observability.ProductionGaDrillMatrix.failureInjectionSummary());
        summary.put("versionCompatibilityMatrix", kr.lunaf.cloudislands.common.observability.VersionCompatibilityPolicy.matrixSummary());
        summary.put("versionRollingUpgradeOrder", kr.lunaf.cloudislands.common.observability.VersionCompatibilityPolicy.rollingUpgradeOrderSummary());
        summary.put("versionSupportedPaper", kr.lunaf.cloudislands.common.observability.VersionCompatibilityPolicy.SUPPORTED_PAPER_VERSION);
        summary.put("versionSupportedVelocity", kr.lunaf.cloudislands.common.observability.VersionCompatibilityPolicy.SUPPORTED_VELOCITY_VERSION);
        summary.put("versionSupportedJava", kr.lunaf.cloudislands.common.observability.VersionCompatibilityPolicy.SUPPORTED_JAVA_VERSION);
        summary.put("versionFoliaSupportPolicy", kr.lunaf.cloudislands.common.observability.VersionCompatibilityPolicy.FOLIA_SUPPORT_POLICY);
        summary.put("versionMinecraftUpdatePolicy", kr.lunaf.cloudislands.common.observability.VersionCompatibilityPolicy.MINECRAFT_UPDATE_POLICY);
        summary.put("versionProtocolChangePolicy", kr.lunaf.cloudislands.common.observability.VersionCompatibilityPolicy.PROTOCOL_CHANGE_POLICY);
        summary.put("versionMinorCompatibilityPolicy", kr.lunaf.cloudislands.common.observability.VersionCompatibilityPolicy.MINOR_COMPATIBILITY_POLICY);
        summary.put("integrationDistributedHookPolicy", kr.lunaf.cloudislands.common.integration.CloudIntegrationPolicy.DISTRIBUTED_HOOK_POLICY);
        summary.put("integrationKnownPlugins", String.join(",", kr.lunaf.cloudislands.common.integration.CloudIntegrationPolicy.knownPlugins()));
        summary.put("integrationCoreProtectPolicy", kr.lunaf.cloudislands.common.integration.CloudIntegrationPolicy.COREPROTECT_POLICY);
        summary.put("integrationWorldEditPolicy", kr.lunaf.cloudislands.common.integration.CloudIntegrationPolicy.WORLDEDIT_POLICY);
        summary.put("integrationCustomItemPolicy", kr.lunaf.cloudislands.common.integration.CloudIntegrationPolicy.CUSTOM_ITEM_POLICY);
        summary.put("integrationStackerPolicy", kr.lunaf.cloudislands.common.integration.CloudIntegrationPolicy.STACKER_POLICY);
        summary.put("integrationPermissionPolicy", kr.lunaf.cloudislands.common.integration.CloudIntegrationPolicy.PERMISSION_POLICY);
        summary.put("integrationActivityPolicy", kr.lunaf.cloudislands.common.integration.CloudIntegrationPolicy.ACTIVITY_POLICY);
        summary.put("integrationEconomyPolicy", kr.lunaf.cloudislands.common.integration.CloudIntegrationPolicy.ECONOMY_POLICY);
        summary.put("addonRegistryPolicy", "paper-addon-registers-core-stores-snapshot-only");
        summary.put("addonStateOwnershipPolicy", "core-persists-addon-key-value-state-without-addon-business-logic");
        summary.put("addonRemovalSafetyPolicy", "missing-addon-metadata-or-state-must-not-block-island-lifecycle");
        summary.put("addonStateFailureIsolationPolicy", "addon-state-storage-outages-return-503-without-affecting-island-lifecycle");
        summary.put("addonExtensionModel", "optional-external-plugin-using-cloudislands-api");
        summary.put("addonApiLookupPolicy", "cloudislands-provider-first-bukkit-servicesmanager-fallback");
        summary.put("addonApiContractVersion", kr.lunaf.cloudislands.api.CloudIslandsApiContract.CONTRACT_VERSION);
        summary.put("addonApiContractCompatibility", kr.lunaf.cloudislands.api.CloudIslandsApiContract.metadataCompatibilityStatus(kr.lunaf.cloudislands.api.CloudIslandsApiContract.metadata()));
        summary.put("addonApiContractCompatible", kr.lunaf.cloudislands.api.CloudIslandsApiContract.compatibleMetadata(kr.lunaf.cloudislands.api.CloudIslandsApiContract.metadata()));
        summary.put("addonApiRequiredMetadataKeys", kr.lunaf.cloudislands.api.CloudIslandsApiContract.requiredMetadataKeysCsv());
        summary.put("addonApiReadPolicy", kr.lunaf.cloudislands.api.CloudIslandsApiContract.READ_POLICY);
        summary.put("addonApiWriteAuthority", kr.lunaf.cloudislands.api.CloudIslandsApiContract.WRITE_AUTHORITY);
        summary.put("addonApiSyncEventPolicy", kr.lunaf.cloudislands.api.CloudIslandsApiContract.SYNC_EVENT_POLICY);
        summary.put("addonApiStoragePolicy", kr.lunaf.cloudislands.api.CloudIslandsApiContract.ADDON_STORAGE_POLICY);
        summary.put("addonApiRemovalPolicy", kr.lunaf.cloudislands.api.CloudIslandsApiContract.ADDON_REMOVAL_POLICY);
        summary.put("addonApiReconnectPolicy", kr.lunaf.cloudislands.api.CloudIslandsApiContract.ADDON_RECONNECT_POLICY);
        summary.put("addonJavaPluginApiPolicy", kr.lunaf.cloudislands.api.CloudIslandsApiContract.JAVA_PLUGIN_API_POLICY);
        summary.put("addonInternalApiPolicy", kr.lunaf.cloudislands.api.CloudIslandsApiContract.INTERNAL_API_POLICY);
        summary.put("addonEventApiPolicy", kr.lunaf.cloudislands.api.CloudIslandsApiContract.EVENT_API_POLICY);
        summary.put("addonTimeoutRetryPolicy", kr.lunaf.cloudislands.api.CloudIslandsApiContract.TIMEOUT_RETRY_POLICY);
        summary.put("addonCompatibilityTestkitPolicy", kr.lunaf.cloudislands.api.CloudIslandsApiContract.COMPATIBILITY_TESTKIT_POLICY);
        summary.put("addonCoreAuthPolicy", kr.lunaf.cloudislands.api.CloudIslandsApiContract.CORE_AUTH_POLICY);
        summary.put("addonAdminEndpointPolicy", kr.lunaf.cloudislands.api.CloudIslandsApiContract.ADMIN_ENDPOINT_POLICY);
        summary.put("addonNetworkExposurePolicy", kr.lunaf.cloudislands.api.CloudIslandsApiContract.NETWORK_EXPOSURE_POLICY);
        summary.put("addonSecurityPostureSummary", kr.lunaf.cloudislands.api.CloudIslandsApiContract.SECURITY_POSTURE_SUMMARY);
        summary.put("addonTopologyPrivacyPolicy", kr.lunaf.cloudislands.api.CloudIslandsApiContract.TOPOLOGY_PRIVACY_POLICY);
        summary.put("addonConsistencyAuthorityPolicy", kr.lunaf.cloudislands.api.CloudIslandsApiContract.CONSISTENCY_AUTHORITY_POLICY);
        summary.put("addonEventDeliveryPolicy", "core-global-events-to-paper-poller-to-cloudislands-addon-and-bukkit-events");
        summary.put("addonEventCoverage", "pre-create,create,pre-activate,activate,deactivate,migrate,delete,delete-backup-failed,restore,reset,recovery,runtime,pre-visit,visit,invite,member-join,member-left,member-role,member-change,ownership,rename,access,visitor-ban,visitor-kick,flag,permission-check,permission-change,role-catalog,biome,home,warp-create,warp-delete,warp-change,bank,chat,mission,blocks,block-value,level,worth,upgrade,limit,snapshot,template,addon-state,node,core-cache,core-reload,route-ticket");
        summary.put("addonEventBackfillPolicy", "paper-poller-uses-listEventsSince-with-sequence-gap-cache-invalidation");
        summary.put("satisPackaging", "official-external-addon");
        summary.put("satisCoreCoupling", "optional-addon-no-core-runtime-dependency");
        summary.put("satisAddonRemovalPolicy", "core-boots-and-islands-load-without-satis-jar");
        summary.put("satisDataRetentionPolicy", "addon-state-preserved-when-disabled-or-removed");
        summary.put("satisCoreBootRequiresAddon", false);
        summary.put("satisCommandOwner", "optional-satis-paper-addon");
        summary.put("satisCrossNodeStatePolicy", "addon-state-must-be-stored-in-core-api-or-shared-database-not-paper-node-memory");
        summary.put("satisIslandMovePolicy", "when-island-moves-between-island-nodes-addon-remaps-state-to-current-active-world-and-cell");
        summary.put("satisFeatureDisablePolicy", "disabled-features-register-no-commands-gui-listeners-tasks-or-data-writes-and-preserve-existing-data");
        summary.put("satisSuperiorSkyblock2Policy", "no-runtime-dependency-use-cloudislands-public-api-and-addon-spi-only");
        summary.put("satisOperationScenarios", kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.operationScenarioSummary());
        summary.put("satisRecommendedModeReasons", kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.recommendedModeReasonSummary());
        summary.put("satisComponentBoundaries", kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.componentBoundarySummary());
        summary.put("satisFeatureOffRuntimeBlocks", kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.featureOffRuntimeBlockSummary());
        summary.put("satisStateStorageConfig", kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.stateStorageConfigSummary());
        summary.put("satisPlayerExperiencePolicy", kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.playerExperienceBoundarySummary());
        summary.put("satisOfficialFeaturePackPolicy", kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.officialFeaturePackBoundarySummary());
        summary.put("satisNodeMoveRemapFlow", kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.nodeMoveRemapStepSummary());
        summary.put("satisFailureRecoveryFlow", kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.failureRecoveryStepSummary());
        summary.put("satisAddonReconnectFlow", kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.addonReconnectStepSummary());
        summary.put("satisCompletionCriteria", kr.lunaf.cloudislands.common.feature.SatisIntegrationPolicy.completionCriteriaSummary());
        summary.put("satisRecoveryPolicy", "use-last-confirmed-addon-state-after-node-failure-and-avoid-duplicate-ticks-with-core-fencing");
        summary.put("satisAddonAbsentPolicy", "cloudislands-core-and-island-lifecycle-do-not-require-cloudislands-satis-installed");
        summary.put("satisDisabledRuntimePolicy", "disabled-satis-keeps-core-create-route-protect-save-restore-working-without-registering-satis-runtime-components");
        summary.put("satisReinstallPolicy", "preserved-addon-state-can-be-reconnected-when-satis-addon-is-installed-again");
        summary.put("satisStateAuthorityPolicy", "portable-addon-state-is-authoritative-in-core-api-bulk-table-key-value-or-configured-shared-database");
        summary.put("satisMultiNodeSafe", true);
        summary.put("satisNodeCountPolicy", "island-node-count-does-not-change-satis-state-identity-or-storage-authority");
        summary.put("velocitySatisCommandPolicy", "no-direct-satis-command-handler-route-only");
        summary.put("paperSatisCommandPolicy", "addon-registers-own-commands-when-enabled");
        summary.put("finalRequestFlowKeys", kr.lunaf.cloudislands.common.routing.FinalRequestFlowPolicy.flowKeys());
        summary.put("finalRequestFlowIslandCreate", kr.lunaf.cloudislands.common.routing.FinalRequestFlowPolicy.flowSummary("island-create"));
        summary.put("finalRequestFlowIslandHome", kr.lunaf.cloudislands.common.routing.FinalRequestFlowPolicy.flowSummary("island-home"));
        summary.put("finalRequestFlowIslandVisit", kr.lunaf.cloudislands.common.routing.FinalRequestFlowPolicy.flowSummary("island-visit"));
        summary.put("finalRequestFlowSoftFullRouting", kr.lunaf.cloudislands.common.routing.FinalRequestFlowPolicy.flowSummary("soft-full-routing"));
        summary.put("islandPool", config.islandPool());
        summary.put("islandPoolNodeCount", islandPoolNodeCount(config, nodes));
        summary.put("islandPoolRouteCandidateCount", islandPoolRouteCandidateCount(config, nodes));
        summary.put("islandPoolRouteCandidateRecommendedMinimum", islandPoolRouteCandidateRecommendedMinimum(config, nodes));
        summary.put("islandPoolRouteCandidateMinimumStatus", islandPoolRouteCandidateMinimumStatus(config, nodes));
        summary.put("islandPoolRouteCandidateNodeIds", islandPoolRouteCandidateNodeIds(config, nodes));
        summary.put("islandPoolScaleStatus", islandPoolScaleStatus(config, nodes));
        summary.put("islandPoolScaleModel", "dynamic-node-pool-by-node-id");
        summary.put("islandPoolElasticLimitPolicy", kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.SCALE_POLICY);
        summary.put("islandPoolScaleGuidance", "add-island-nodes-with-unique-node-id-unique-velocity-server-name-shared-storage");
        summary.put("islandPoolHorizontalScalePolicy", "no-hardcoded-island-node-count-unique-node-id-unique-velocity-server-name-shared-storage-required");
        summary.put("islandPoolFiveSixNodePolicy", kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.FIVE_SIX_NODE_POLICY);
        summary.put("islandPoolScaleReadinessPolicy", kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.SCALE_READINESS_POLICY);
        summary.put("islandPoolScaleReadinessSummary", kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.scaleReadinessSummary());
        summary.put("islandPoolFiveSixNodeHealthy", islandPoolFiveSixNodeHealthy(config, nodes));
        summary.put("islandPoolFiveSixNodeStatus", islandPoolFiveSixNodeStatus(config, nodes));
        summary.put("islandPlacementPolicy", "deterministic-uuid-shard-cell");
        summary.put("islandPlacementShardCount", IslandPlacement.SHARD_COUNT);
        summary.put("islandPlacementCellsPerAxis", IslandPlacement.CELLS_PER_AXIS);
        summary.put("islandPlacementCollisionPolicy", "uuid-derived-cell-with-runtime-occupied-cell-probing-db-unique-guard-fencing-and-node-lease");
        summary.put("islandNodeHardRules", "pool-match,ready-or-soft-full,fresh-heartbeat,hard-cap-open,activation-queue-open,object-storage-available,template-supported,min-node-version,not-default-identity");
        summary.put("islandNodeScoreWeights", "players=0.25,activeIslands=0.15,mspt=0.25,activationQueue=0.15,chunkLoad=0.10,memory=0.05,recentFailure=0.05");
        summary.put("islandNodeSchemaColumns", "id,pool,velocity_server_name,node_version,state,soft_player_cap,hard_player_cap,reserved_slots,max_active_islands,players,active_islands,mspt,heap_used_mb,heap_max_mb,activation_queue,max_activation_queue,chunk_load_pressure,recent_failure_penalty,object_storage_available,supported_templates,last_heartbeat");
        summary.put("islandNodeExistingRoutePolicy", "active-island-stays-on-current-node-unless-node-missing-stale-down-or-admin-migration");
        summary.put("islandNodeVisitorSoftFullPolicy", "visitors-queue-or-retry-on-soft-full-active-node-members-use-reserved-slots");
        summary.put("redisRolePolicy", kr.lunaf.cloudislands.common.cache.CacheStrategyPolicy.REDIS_ROLE);
        summary.put("redisKeyScope", kr.lunaf.cloudislands.common.cache.CacheStrategyPolicy.REDIS_KEY_SCOPE);
        summary.put("redisTtlSummary", kr.lunaf.cloudislands.common.cache.CacheStrategyPolicy.REDIS_TTL_SUMMARY);
        summary.put("redisConsistencyGuard", kr.lunaf.cloudislands.common.cache.CacheStrategyPolicy.CONSISTENCY_GUARD);
        summary.put("fencingWritePolicy", kr.lunaf.cloudislands.common.security.FencingToken.WRITE_POLICY);
        summary.put("fencingRedisLockPolicy", kr.lunaf.cloudislands.common.security.FencingToken.REDIS_LOCK_POLICY);
        summary.put("nodeProtocolMinSupported", MIN_NODE_PROTOCOL_VERSION);
        summary.put("nodeProtocolCurrent", MAX_NODE_PROTOCOL_VERSION);
        summary.put("nodeProtocolNegotiationPolicy", kr.lunaf.cloudislands.protocol.ProtocolVersion.NEGOTIATION_POLICY);
        summary.put("nodeProtocolHeartbeatField", kr.lunaf.cloudislands.protocol.ProtocolVersion.HEARTBEAT_FIELD);
        summary.put("routingFailureDetailKeys", "pool,nodeCount,readyOrSoftFullNodeCount,storageReadyNodeCount,primaryStorageHealthyNodeCount,storageSaveRetryBacklogNodeCount,storageSaveRetryBacklogTotal,hardCapOpenNodeCount,activeIslandOpenNodeCount,queueOpenNodeCount,defaultIdentityRiskNodeCount,duplicateVelocityServerNameNodeCount,routeCandidateEstimateNodeCount,routeCandidateRecommendedMinimum,routeCandidateShortfall,routeCandidateEstimatePolicy,elasticLimitPolicy,blockReason,physicalNodeNamesExposed");
        summary.put("islandPoolMultiNodeReady", islandPoolMultiNodeReady(config, nodes));
        summary.put("islandPoolDegraded", islandPoolDegraded(config, nodes));
        summary.put("islandPoolRouteCandidateShortfall", islandPoolRouteCandidateShortfall(config, nodes));
        summary.put("islandPoolRouteCandidateBlockSummary", islandPoolRouteCandidateBlockSummary(config, nodes));
        summary.put("islandPoolBlockedNodeIds", islandPoolBlockedNodeIds(config, nodes));
        summary.put("islandPoolDuplicateVelocityServerNameNodeCount", islandPoolDuplicateVelocityServerNameNodeCount(config, nodes));
        summary.put("islandPoolDefaultNodeIdentityRiskCount", islandPoolDefaultNodeIdentityRiskCount(config, nodes));
        summary.put("softFullPolicy", config.softFullPolicy());
        summary.put("hardFullPolicy", config.hardFullPolicy());
        summary.put("softFullNewActivationAvoided", avoidsSoftFullNewActivations(config.softFullPolicy()));
        summary.put("hardFullNewActivationAllowed", allowsHardFullNewActivations(config.hardFullPolicy()));
        summary.put("nodeAllocatorNewActivationFallback", "READY nodes first, SOFT_FULL skipped by default so Island-2/next ready node receives new work when Island-1 is soft-full");
        summary.put("migrationPolicy", config.migrationPolicy());
        summary.put("superiorSkyblock2MigrationEnabled", config.superiorSkyblock2MigrationEnabled());
        summary.put("superiorSkyblock2MigrationInputOnly", true);
        summary.put("superiorSkyblock2RuntimeDependency", false);
        summary.put("superiorSkyblock2RuntimePolicy", "migration-input-only-no-runtime-hooks");
        summary.put("superiorSkyblock2ReplacementFeatureCount", kr.lunaf.cloudislands.common.feature.SuperiorSkyblockReplacementFeaturePolicy.requiredFeatureCount());
        summary.put("superiorSkyblock2ReplacementFeatures", kr.lunaf.cloudislands.common.feature.SuperiorSkyblockReplacementFeaturePolicy.requiredFeatureKeys());
        summary.put("superiorSkyblock2MigrationTargets", kr.lunaf.cloudislands.common.feature.SuperiorSkyblockReplacementFeaturePolicy.migrationTargetSummary());
        summary.put("superiorSkyblock2MigrationFlow", kr.lunaf.cloudislands.common.feature.SuperiorSkyblockReplacementFeaturePolicy.migrationStepSummary());
        summary.put("superiorSkyblock2MigrationCommands", kr.lunaf.cloudislands.common.feature.SuperiorSkyblockReplacementFeaturePolicy.migrationCommandSummary());
        summary.put("superiorSkyblock2MigrationEndpoints", "scan,status,dryrun,extract,import,verify,rollback");
        summary.put("superiorSkyblock2MigrationStatusEndpoint", "/v1/admin/migrations/superiorskyblock2/status");
        summary.put("superiorSkyblock2MigrationRollbackPolicy", "last-successful-import-only-consume-plan-after-success");
        summary.put("routeTicketTtlSeconds", config.routeTicketTtl().toSeconds());
        summary.put("routePreparingTicketTtlSeconds", config.routePreparingTicketTtl().toSeconds());
        summary.put("routeTicketOneTimeConsume", kr.lunaf.cloudislands.protocol.route.RouteTicketPolicy.ONE_TIME_CONSUME);
        summary.put("routeTicketNonceRequired", kr.lunaf.cloudislands.protocol.route.RouteTicketPolicy.NONCE_REQUIRED);
        summary.put("routeTicketTargetNodeRequired", kr.lunaf.cloudislands.protocol.route.RouteTicketPolicy.TARGET_NODE_REQUIRED);
        summary.put("routeTicketOneTimePolicy", kr.lunaf.cloudislands.protocol.route.RouteTicketPolicy.ONE_TIME_POLICY);
        summary.put("routeTicketNoncePolicy", kr.lunaf.cloudislands.protocol.route.RouteTicketPolicy.NONCE_POLICY);
        summary.put("routeTicketArrivalConsumePolicy", kr.lunaf.cloudislands.protocol.route.RouteTicketPolicy.ARRIVAL_CONSUME_POLICY);
        summary.put("routeTicketDirectAccessPolicy", kr.lunaf.cloudislands.protocol.route.RouteTicketPolicy.DIRECT_ACCESS_POLICY);
        summary.put("routeTicketReplayPolicy", kr.lunaf.cloudislands.protocol.route.RouteTicketPolicy.REPLAY_POLICY);
        summary.put("routeTicketConsumeEndpoint", "/v1/routes/consume");
        summary.put("routeSessionConsumeEndpoint", "/v1/routes/session/consume");
        summary.put("routeSessionPreLoginGuard", "paper-async-prelogin-find-session-and-playerjoin-consume-session");
        summary.put("heartbeatTimeoutSeconds", config.heartbeatTimeout().toSeconds());
        summary.put("leaseDurationSeconds", config.leaseDuration().toSeconds());
        summary.put("cacheTierPolicy", "L1=paper-velocity-local-memory,L2=redis,L3=postgresql-mysql-mariadb-core-jdbc");
        summary.put("cacheAuthoritativeStorePolicy", "database-or-core-api-is-authority-redis-and-local-memory-are-discardable");
        summary.put("redisCacheTtlPolicy", "route-ticket=30s,player-island=300s,island-summary=60s,permissions=30s,locks=10-60s");
        summary.put("redisCacheTtlMillis", "serverHeartbeat=" + kr.lunaf.cloudislands.common.cache.RedisTtls.SERVER_HEARTBEAT_MILLIS
                + ",routeTicket=" + kr.lunaf.cloudislands.common.cache.RedisTtls.ROUTE_TICKET_MILLIS
                + ",playerIsland=" + kr.lunaf.cloudislands.common.cache.RedisTtls.PLAYER_ISLAND_MILLIS
                + ",playerProfile=" + kr.lunaf.cloudislands.common.cache.RedisTtls.PLAYER_PROFILE_MILLIS
                + ",islandSummary=" + kr.lunaf.cloudislands.common.cache.RedisTtls.ISLAND_SUMMARY_MILLIS
                + ",islandMetadata=" + kr.lunaf.cloudislands.common.cache.RedisTtls.ISLAND_METADATA_MILLIS
                + ",islandRuntime=" + kr.lunaf.cloudislands.common.cache.RedisTtls.ISLAND_RUNTIME_MILLIS
                + ",islandPermissions=" + kr.lunaf.cloudislands.common.cache.RedisTtls.ISLAND_PERMISSIONS_MILLIS
                + ",lockMin=" + kr.lunaf.cloudislands.common.cache.RedisTtls.LOCK_MIN_MILLIS
                + ",lockMax=" + kr.lunaf.cloudislands.common.cache.RedisTtls.LOCK_MAX_MILLIS);
        summary.put("redisKeyPolicy", "ci:server:{nodeId}:*,ci:player:{uuid}:*,ci:island:{islandId}:*,ci:lock:*,ci:stream:*");
        summary.put("cacheInvalidationSource", "core-write-transaction-then-global-event");
        summary.put("cacheInvalidationEvents", "IslandMemberChanged,IslandFlagChanged,IslandPermissionChanged,IslandWarpChanged,IslandRuntimeChanged,IslandDeleted");
        summary.put("cacheInvalidationEventFields", "cacheTargets,cacheKeys,cachePolicy");
        summary.put("cacheInvalidationFanout", "core-event-stream>paper-event-poller>velocity-route-cache-if-affected>local-cache-delete");
        summary.put("cacheInvalidationTargets", "player_uuid->island_id,island_id->summary,island_id->runtime,island_id->members,island_id->permissions,island_id->flags,island_id->warps,node_id->heartbeat");
        summary.put("cacheInvalidationRedisPatterns", "ci:player:*:island,ci:player:*:profile,ci:player-name:*:profile,ci:addon:*:state,ci:island:*:summary,ci:island:*:runtime,ci:island:*:members,ci:island:*:permissions,ci:island:*:flags,ci:island:*:warps,ci:island:*:addon-state,ci:island:*:route-tickets,ci:rankings:*");
        summary.put("addonStateGlobalCacheKey", "ci:addon:{addonId}:state");
        summary.put("addonStateIslandCacheKey", "ci:island:{islandId}:addon-state");
        summary.put("addonStateCacheInvalidationApi", "CacheInvalidationPlan.redisKeysFor(eventType,islandId,addonId)");
        summary.put("cacheRedisDownPolicy", "degraded-db-direct-read-no-data-loss-event-propagation-delayed-jobs-and-heartbeats-limited");
        summary.put("cacheCoreApiDownPolicy", "active-island-local-protection-continues-new-route-and-writes-limited");
        summary.put("redisStreamPolicy", "jobs,events,audit-append-only-observability");
        summary.put("globalEventTypes", "IslandCreated,IslandDeleted,IslandActivated,IslandDeactivated,IslandMigrated,IslandMemberChanged,IslandFlagChanged,IslandLevelUpdated,IslandSnapshotCreated,NodeStateChanged,RouteTicketCreated,RouteSessionPublished,RouteTicketConsumed,RouteTicketFailed,RouteTicketCleared");
        summary.put("globalEventTypeKeys", globalEventTypeKeys());
        summary.put("globalEventRecoveryKeys", "ISLAND_RUNTIME_CHANGED,ISLAND_RECOVERY_REQUIRED,ISLAND_REPAIRED,NODE_STATE_CHANGED");
        summary.put("globalEventAddonKeys", "ADDON_STATE_CHANGED");
        summary.put("routeMetricsTargetServerName", true);
        summary.put("routeMetricsTargetServerNameEvents", "RouteTicketCreated,RouteSessionPublished,RouteTicketConsumed,RouteTicketFailed");
        summary.put("routeMetricsRequestedNode", true);
        summary.put("routeMetricsRequestedNodeEvents", "RouteTicketFailed");
        summary.put("distributedLockPolicy", "redis-fast-lock-plus-postgresql-row-lock");
        summary.put("fencingTokenPolicy", "island_runtime.fencing_token-rejects-stale-node-writes");
        summary.put("jobCompletionContract", kr.lunaf.cloudislands.protocol.job.IslandJobCompletionPolicy.CONTRACT);
        summary.put("jobCompletionFencingTokenKey", kr.lunaf.cloudislands.protocol.job.IslandJobCompletionPolicy.FENCING_TOKEN_KEY);
        summary.put("jobCompletionStaleReasons", kr.lunaf.cloudislands.protocol.job.IslandJobCompletionPolicy.STALE_FENCING_TOKEN + "," + kr.lunaf.cloudislands.protocol.job.IslandJobCompletionPolicy.STALE_NODE_COMPLETION + "," + kr.lunaf.cloudislands.protocol.job.IslandJobCompletionPolicy.RUNTIME_NOT_ACCEPTING_COMPLETION);
        summary.put("staleWritePolicy", "current-fencing-token-required-before-snapshot-or-runtime-write");
        summary.put("snapshotKeepLatest", config.snapshotKeepLatest());
        summary.put("snapshotKeepHourly", snapshotPolicy.keepHourly());
        summary.put("snapshotKeepDaily", snapshotPolicy.keepDaily());
        summary.put("snapshotKeepWeekly", snapshotPolicy.keepWeekly());
        summary.put("snapshotKeepManual", snapshotPolicy.keepManual());
        summary.put("snapshotCompress", snapshotPolicy.compress());
        summary.put("snapshotChecksumAlgorithm", snapshotPolicy.checksumAlgorithm());
        summary.put("snapshotRetentionMode", "hourly-daily-weekly-manual");
        summary.put("snapshotAutomaticTriggerPolicy", kr.lunaf.cloudislands.storage.snapshot.SnapshotOperationPolicy.AUTOMATIC_TRIGGER_POLICY);
        summary.put("snapshotRequiredTriggerReasons", kr.lunaf.cloudislands.storage.snapshot.SnapshotOperationPolicy.automaticTriggerReasonSummary());
        summary.put("snapshotManualTriggerReason", "MANUAL");
        summary.put("snapshotPreRestoreReason", "BEFORE_RESTORE");
        summary.put("snapshotRestorePipeline", kr.lunaf.cloudislands.storage.snapshot.SnapshotOperationPolicy.RESTORE_PIPELINE_POLICY);
        summary.put("snapshotRestoringLockState", kr.lunaf.cloudislands.storage.snapshot.SnapshotOperationPolicy.RESTORING_LOCK_STATE);
        summary.put("snapshotRuntimeResetPolicy", kr.lunaf.cloudislands.storage.snapshot.SnapshotOperationPolicy.RUNTIME_RESET_POLICY);
        summary.put("snapshotRollbackSteps", kr.lunaf.cloudislands.storage.snapshot.SnapshotOperationPolicy.rollbackStepSummary());
        summary.put("coreApiAuthPolicy", "token-or-mtls-required");
        summary.put("coreApiTokenConfigured", (config.coreToken() != null && !config.coreToken().isBlank()));
        summary.put("coreApiMtlsRequired", config.requireMtls());
        summary.put("coreApiAuthConfigured", coreApiAuthConfigured(config));
        summary.put("coreApiAuthLockoutRisk", !coreApiAuthConfigured(config));
        summary.put("adminPermissionPolicy", "separate-admin-permission-per-endpoint");
        summary.put("auditLogPolicy", "record-admin-player-and-system-actions");
        summary.put("controlChannelPolicy", "http-or-grpc-plus-redis-streams");
        summary.put("pluginMessagingPolicy", "not-used-for-critical-island-control");
        summary.put("requiredSecurityControls", String.join(",", kr.lunaf.cloudislands.common.security.BackendAccessPolicy.requiredSecurityControls()));
        summary.put("velocityForwardingSecurityPolicy", kr.lunaf.cloudislands.common.security.BackendAccessPolicy.MODERN_FORWARDING_POLICY);
        summary.put("paperDirectAccessSecurityPolicy", kr.lunaf.cloudislands.common.security.BackendAccessPolicy.PAPER_DIRECT_ACCESS_POLICY);
        summary.put("coreApiSecurityPolicy", kr.lunaf.cloudislands.common.security.BackendAccessPolicy.CORE_API_AUTH_POLICY);
        summary.put("infrastructureExposureSecurityPolicy", kr.lunaf.cloudislands.common.security.BackendAccessPolicy.INFRASTRUCTURE_EXPOSURE_POLICY);
        summary.put("pluginMessagingSecurityPolicy", kr.lunaf.cloudislands.common.security.BackendAccessPolicy.PLUGIN_MESSAGING_POLICY);
        summary.put("pluginMessagingAllowedUse", "emergency-proxy-assist-only");
        summary.put("pluginMessagingForbiddenUse", "island-create-delete-save-migrate-routing-authority");
        summary.put("paperAgentRolePolicy", "LOBBY handles menus-and-query-flow,ISLAND_NODE handles-world-runtime-protection-save-teleport");
        summary.put("paperLobbyRolePolicy", "no-island-world-execution-no-runtime-lease-no-shard-cell-ownership");
        summary.put("paperIslandNodeRolePolicy", "activate-save-snapshot-shard-cell-preload-protection-route-ticket-consume");
        summary.put("velocityCommandOwnershipPolicy", "/is-and-/섬-route-entry-owned-by-velocity-before-paper-fallback");
        summary.put("paperCommandFallbackPolicy", "paper-agent-keeps-local-gui-protection-and-bungee-connect-fallback-only");
        summary.put("createIslandFlowPolicy", "velocity-command-core-transaction-player-lock-node-allocator-create-job-agent-claim-template-restore-cell-runtime-active-route-ticket-ready-connect-teleport");
        summary.put("homeRouteFlowPolicy", "velocity-command-core-runtime-check-active-node-or-best-node-activation-route-ticket-ready-connect-paper-teleport");
        summary.put("visitRouteFlowPolicy", "target-island-lookup-public-ban-permission-check-active-or-activate-visitor-ticket-connect-visitor-spawn");
        summary.put("softFullRoutingPolicy", "new-and-inactive-islands-avoid-soft-full-nodes-active-members-may-use-reserved-slots-visitors-queue-or-deny");
        summary.put("newActivationSoftFullPolicy", config.softFullPolicy());
        summary.put("newActivationSoftFullAvoided", avoidsSoftFullNewActivations(config.softFullPolicy()));
        summary.put("newActivationHardFullPolicy", config.hardFullPolicy());
        summary.put("newActivationHardFullAllowed", allowsHardFullNewActivations(config.hardFullPolicy()));
        summary.put("portableIslandPolicy", "islands-are-global-portable-bundles-not-fixed-to-a-server-node");
        summary.put("portableIslandResourceModel", kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.RESOURCE_MODEL);
        summary.put("portableIslandBundleModel", kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.BUNDLE_MODEL);
        summary.put("portableIslandNodeModel", kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.NODE_MODEL);
        summary.put("portableIslandPlayerVisibilityPolicy", kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.PLAYER_VISIBILITY_POLICY);
        summary.put("portableIslandScalePolicy", kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.SCALE_POLICY);
        summary.put("portableIslandFiveSixNodePolicy", kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.FIVE_SIX_NODE_POLICY);
        summary.put("portableIslandScaleReadinessPolicy", kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.SCALE_READINESS_POLICY);
        summary.put("portableIslandSoftFullPolicy", kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.SOFT_FULL_POLICY);
        summary.put("portableIslandDesignEffects", kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.designEffectSummary());
        summary.put("portableIslandDefinition", kr.lunaf.cloudislands.common.island.IslandPortabilityPolicy.ONE_LINE_DEFINITION);
        summary.put("nodeScaleOutPolicy", "add-island-nodes-with-unique-node-id-and-velocity-server-name-then-allocator-can-route-new-or-inactive-islands-there");
        summary.put("rankingUpdatePolicy", kr.lunaf.cloudislands.coreservice.ranking.RankingRecalculationService.UPDATE_POLICY);
        summary.put("blockValuePolicy", kr.lunaf.cloudislands.coreservice.ranking.RankingRecalculationService.BLOCK_VALUE_POLICY);
        summary.put("rankingFullScanPolicy", kr.lunaf.cloudislands.coreservice.ranking.RankingRecalculationService.FULL_SCAN_POLICY);
        summary.put("rankingCachePolicy", kr.lunaf.cloudislands.coreservice.ranking.RankingRecalculationService.CACHE_POLICY);
        summary.put("rankingDirtyBatchLimit", kr.lunaf.cloudislands.coreservice.ranking.DirtyRankingRecalculationTask.BATCH_LIMIT);
        summary.put("upgradePolicy", kr.lunaf.cloudislands.coreservice.upgrade.UpgradePolicy.CONFIG_DRIVEN_POLICY);
        summary.put("upgradeTypePolicy", kr.lunaf.cloudislands.coreservice.upgrade.UpgradePolicy.SUPPORTED_TYPE_POLICY);
        summary.put("upgradeEffectPolicy", kr.lunaf.cloudislands.coreservice.upgrade.UpgradePolicy.EFFECT_APPLICATION_POLICY);
        summary.put("upgradePurchasePolicy", kr.lunaf.cloudislands.coreservice.upgrade.IslandUpgradeService.PURCHASE_POLICY);
        summary.put("upgradeEconomyPolicy", kr.lunaf.cloudislands.coreservice.upgrade.IslandUpgradeService.ECONOMY_ABSTRACTION_POLICY);
        summary.put("paperUpgradeEconomyPolicy", "paper-agent-uses-economy-bridge-for-player-facing-upgrade-purchase");
        summary.put("generatorPolicy", "paper-agent-local-generator-rules-by-island-upgrade-level");
        summary.put("superiorSkyblock2ReplacementPolicy", "built-in-cloudislands-modules-replace-superiorskyblock2-runtime-dependency");
        summary.put("superiorSkyblock2ReplacementFeatures", "create,template-select,delete,reset,home,multiple-homes,visit,random-visit,public-private,visitor-ban,visitor-kick,member-invite,member-kick,roles-permissions,custom-roles,flags,warps,ranking,level,worth,block-values,upgrades,size-expansion,border,biome,bank,island-chat,team-chat,missions,challenges,generator-upgrades,spawner-limits,hopper-limits,entity-limits,redstone-limits,island-logs,admin-recovery,snapshots-rollback,migration,server-drain,distributed-api,web-api,external-java-api");
        summary.put("superiorSkyblock2ReplacementFeatureGate", "core-config-and-addon-feature-flags-can-disable-optional-satis-compatible-features");
        summary.put("infrastructureExposurePolicy", "redis-postgresql-object-storage-private-only");
        summary.put("publicBindRiskPolicy", "require-ip-allowlist-or-private-bind");
        summary.put("adminApiEnabled", config.adminApiEnabled());
        summary.put("requireMtls", config.requireMtls());
        summary.put("ipAllowlistEnabled", (config.ipAllowlist() != null && !config.ipAllowlist().isBlank()));
        summary.put("requiredSecurityControls", String.join(",", kr.lunaf.cloudislands.common.security.BackendAccessPolicy.requiredSecurityControls()));
        summary.put("pluginMessagingSecurityPolicy", kr.lunaf.cloudislands.common.security.BackendAccessPolicy.PLUGIN_MESSAGING_POLICY);
        summary.put("rateLimitRequests", config.rateLimitRequests());
        summary.put("rateLimitWindowSeconds", config.rateLimitWindow().toSeconds());
        return SimpleJson.stringify(summary);
    }


    private static boolean avoidsSoftFullNewActivations(String policy) {
        return policy == null
            || policy.isBlank()
            || policy.equalsIgnoreCase("AVOID_NEW_ACTIVATIONS")
            || policy.equalsIgnoreCase("READY_ONLY");
    }

    private static boolean allowsHardFullNewActivations(String policy) {
        return policy != null
            && (policy.equalsIgnoreCase("ALLOW_NEW_ACTIVATIONS")
                || policy.equalsIgnoreCase("ALLOW")
                || policy.equalsIgnoreCase("IGNORE_HARD_FULL"));
    }
}
