package kr.lunaf.cloudislands.coreservice.security.permission;

public enum AdminPermission {
    NODE_DRAIN,
    NODE_UNDRAIN,
    ISLAND_ACTIVATE,
    ISLAND_DEACTIVATE,
    ISLAND_MIGRATE,
    ISLAND_SNAPSHOT,
    ISLAND_RESTORE,
    ISLAND_QUARANTINE,
    ISLAND_DELETE,
    ISLAND_REPAIR,
    ISLAND_TELEPORT,
    AUDIT_READ,
    JOB_MANAGE,
    ROUTE_MANAGE,
    CACHE_CLEAR,
    MIGRATION_MANAGE,
    PLAYER_MANAGE,
    ECONOMY_MANAGE,
    TEMPLATE_MANAGE
}
